import { useState } from 'react';
import type { StudentProfile } from '../../hooks/useLearningProgress';
import type { StoredProgress } from '../../hooks/progressMigration';
import { buildStudentSubmission, discardPendingSubmission, readPendingSubmission, submitStudentProgress } from './submissionService';
import type { SubmissionPayload } from './types';

interface Props { profile?: StudentProfile; progress: StoredProgress; onClose: () => void; onSubmitted: (id: string) => void; }
export function SubmissionDialog({ profile, progress, onClose, onSubmitted }: Props) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [submissionId, setSubmissionId] = useState<string>(); const [receiptAt, setReceiptAt] = useState<string>(); const [, setPendingRevision] = useState(0);
  const payloadResult: { payload: SubmissionPayload } | { error: string } = profile ? (() => { try { return { payload: buildStudentSubmission(profile, progress) }; } catch (cause) { return { error: cause instanceof Error ? cause.message : '제출 자료를 준비하지 못했어요.' }; } })() : { error: '먼저 학생 정보를 입력해 주세요.' };
  const payload = 'payload' in payloadResult ? payloadResult.payload : undefined;
  const pending = profile ? readPendingSubmission(profile.id) : undefined;
  const preview = pending?.payload ?? payload;
  const submit = async () => { if (!profile) return; setBusy(true); setError(''); try { const result = await submitStudentProgress(profile, progress, submissionId); setSubmissionId(result.id); setReceiptAt(result.receiptAt); onSubmitted(result.id); } catch (cause) { setError(cause instanceof Error ? cause.message : '제출에 실패했어요.'); } finally { setBusy(false); } };
  return <div className="dialog-backdrop" role="presentation" onClick={() => { if (!busy) onClose(); }}><section className="update-dialog submission-dialog" role="dialog" aria-modal="true" aria-labelledby="submission-title" onClick={(event) => event.stopPropagation()}><div className="dialog-header"><div><p className="eyebrow">ASSIGNMENT SUBMISSION</p><h2 id="submission-title">과제 제출</h2></div><button className="icon-button" aria-label="과제 제출 닫기" disabled={busy} onClick={onClose}>×</button></div>{!profile ? <><p>먼저 상단의 로그인에서 소속(학교)과 이름을 입력해 주세요.</p><div className="dialog-actions"><button className="primary-button gi-pulse" onClick={onClose}>확인</button></div></> : <><p className="dialog-lead"><strong>{pending ? `${pending.payload.school} · ${pending.payload.name}` : `${profile.school} · ${profile.name}`}</strong>{pending ? ' 이전에 준비한 제출을 다시 시도합니다.' : '으로 현재 브라우저의 학습 결과를 제출합니다.'}</p><div className="submission-summary"><span>필수 단계 완료</span><strong>{preview?.completedRequiredCount ?? 0}/{preview?.requiredLessonCount ?? 0}</strong><small>읽기·실행·도전 결과와 제출 시점의 답 코드를 함께 저장합니다.</small></div>{pending && !submissionId && <div className="pending-actions"><p className="privacy-callout">이전에 실패했거나 응답을 잃은 제출이 남아 있습니다. 현재 편집 내용과 다른 이전 스냅샷을 그대로 재시도합니다.</p><button className="text-button" disabled={busy} onClick={() => { discardPendingSubmission(profile.id); setPendingRevision((value) => value + 1); }}>이전 제출을 버리고 현재 내용으로 새 제출</button></div>}<p className="privacy-callout">제출 버튼을 누르면 학교, 이름, 단계별 진도, 답 코드가 Firebase에 저장됩니다. 제출 전에는 아무 자료도 전송하지 않습니다.</p>{'error' in payloadResult && !pending && <p className="form-error" role="alert">{payloadResult.error}</p>}{error && <p className="form-error" role="alert">{error}</p>}{submissionId && <p className="success-callout" role="status">제출 접수 확인: {submissionId}{receiptAt ? ` · ${new Date(receiptAt).toLocaleString('ko-KR')}` : ''}</p>}<div className="dialog-actions"><button className="secondary-button" disabled={busy} onClick={onClose}>닫기</button><button className="primary-button gi-pulse" disabled={busy || (!payload && !pending)} onClick={submit}>{busy ? '제출 중…' : submissionId ? '같은 제출 다시 확인' : pending ? '이전 제출 재시도' : '과제 제출'}</button></div></>}</section></div>;
}
