import { chapter, makeLesson } from './lessonFactory';

type RuntimeCheck = NonNullable<import('./types').Challenge['runtimeCheck']>;
type Checks = NonNullable<import('./types').Challenge['checks']>;

const challenge = (prompt: string, hint: string, runtimeCheck: RuntimeCheck, feedback: string, checks: Checks = [{ mode: 'changed', value: '', feedback }]) => ({ prompt, hint, runtimeCheck, checks });
const example = (body: string, code: string) => ({ type: 'example' as const, title: '예제 코드 한 줄씩 읽기', body, code });

export const chapter11 = chapter(11, '실생활 문제 해결', [
  makeLesson(11, 1, '동영상 시간을 분·초로', '동영상의 재생 시간인 초를 분과 초로 바꾸어 봅니다. 60으로 나눈 몫은 분, 남은 나머지는 초가 됩니다.', 'challenge', 'total_seconds = 185\nminutes = total_seconds // 60\nseconds = total_seconds % 60\nprint(f"{minutes}분 {seconds}초")', '3분 5초', challenge('total_seconds를 다른 양의 정수 초로 바꾸고 그 값에 맞는 분과 초가 출력되게 하세요.', '첫 줄의 185만 다른 양의 정수로 바꾸세요. 예: `total_seconds = 245`처럼 쓰고, `//`와 `%` 계산 줄은 그대로 둡니다. f-string은 f를 붙인 문자열의 `{minutes}`, `{seconds}` 자리에 변수 값을 넣어 보여 주는 방법이에요. 마지막 줄은 분과 초가 붙은 형태로 출력해야 해요.', 'time', '다른 영상 시간도 몫과 나머지로 정확히 바꾸었어요.'), [{ type: 'explanation', title: '생활 속 질문', body: '185초짜리 영상은 몇 분 몇 초일까요? 실행 전에 60초씩 묶어 손으로 예상해 봅니다.' }, example('첫 줄 `total_seconds = 185`는 전체 초를 변수에 담아요. 둘째 줄 `minutes = total_seconds // 60`은 60으로 나눈 몫을 분에 담아요. 셋째 줄 `seconds = total_seconds % 60`은 남은 나머지를 초에 담아요. 마지막 `print(f"{minutes}분 {seconds}초")`는 f-string으로 두 변수와 글자를 한 줄에 보여 줘요. 실행 뒤 출력창에서 3분 5초인지 관찰해요.', 'total_seconds = 185\nminutes = total_seconds // 60\nseconds = total_seconds % 60\nprint(f"{minutes}분 {seconds}초")')], [['//', '나눗셈에서 몫을 구하는 연산자'], ['%', '나눗셈 뒤에 남는 나머지를 구하는 연산자'], ['변수', '값을 담아 두는 이름표'], ['f-string', '문자열 안의 중괄호에 변수 값을 넣어 보여 주는 방법'], ['print()', '값을 화면에 보여 주는 함수']]),
  makeLesson(11, 2, '오늘 남은 용돈은?', '처음 가진 용돈에서 첫 번째 지출을 빼고, 두 번째 지출을 직접 추가해 남은 돈을 계산합니다.', 'challenge', 'money = 5000\nmoney -= 1800\nprint(f"남은 용돈: {money}원")', '남은 용돈: 3200원', challenge('두 번째 지출을 `-=` 한 줄로 추가하세요. 1원부터 3,200원까지의 금액을 골라 최종 잔액을 계산하세요.', '첫 지출 줄 아래에 `money -= 300`처럼 새 줄을 추가하세요. `-=`는 현재 변수에서 오른쪽 값을 빼 다시 저장하는 기호예요. f-string 대신 `print("남은 용돈:", money, "원")`으로 써도 됩니다.', 'allowance', '두 번의 지출을 반영해 남은 용돈을 계산했어요.'), [{ type: 'explanation', title: '생활 속 질문', body: '5,000원에서 1,800원을 먼저 쓰면 3,200원이 남아요. 여기에 두 번째 지출을 한 줄 추가하면 마지막 잔액이 달라집니다. 두 번째 지출은 1원 이상 3,200원 이하로 골라 봅니다.' }, example('첫 줄 `money = 5000`은 처음 용돈이에요. 둘째 줄 `money -= 1800`은 첫 지출을 빼요. 도전에서 그 아래에 `money -= 300` 같은 두 번째 지출 줄을 추가해요. 마지막 줄은 남은 값을 f-string으로 출력해요. 시작 결과는 3,200원이고, 두 번째 지출을 추가하면 그 금액만큼 줄어야 해요.', 'money = 5000\nmoney -= 1800\nprint(f"남은 용돈: {money}원")')], [['-=', '현재 값에서 오른쪽 값을 빼 다시 저장하는 기호'], ['변수', '값을 담아 두는 이름표'], ['f-string', '문자열 안의 중괄호에 변수 값을 넣는 방법'], ['print()', '값을 화면에 보여 주는 함수']]),
  makeLesson(11, 3, '간식을 살 수 있을까요?', '가진 돈과 간식 가격을 비교해 살 수 있는지 알려 줍니다.', 'challenge', 'money = 2000\nprice = 1500\nif money >= price:\n    print("살 수 있어요")\nelse:\n    print("돈이 부족해요")', '살 수 있어요', challenge('money를 price보다 적은 금액으로 바꾸어 부족 안내를 확인하세요. 도전 통과는 money가 price보다 작은 경우이며, 같은 금액은 추가 관찰로 확인해요.', '첫 줄의 2000을 0 이상인 다른 금액으로 바꾸세요. 예: `money = 1000`이면 `money >= price`가 거짓이라 도전 통과예요. `money = 1500`처럼 가격과 같은 금액으로 바꾸면 살 수 있다는 경계도 관찰할 수 있어요.', 'snack', '돈의 크기에 맞는 조건 안내를 확인했어요.'), [{ type: 'explanation', title: '생활 속 질문', body: '가진 돈이 가격보다 많거나 같으면 살 수 있고, 그렇지 않으면 돈이 부족하다고 알려 줘야 해요. 같은 금액인 경계도 확인합니다.' }, example('첫째 줄 `money = 2000`은 가진 돈, 둘째 줄 `price = 1500`은 간식 가격이에요. `if money >= price:`는 돈이 가격보다 크거나 같은지 묻는 조건이에요. 들여쓴 첫 `print()`는 조건이 맞을 때 실행돼요. `else:` 아래 들여쓴 `print()`는 조건이 아닐 때 실행돼요.', 'money = 2000\nprice = 1500\nif money >= price:\n    print("살 수 있어요")\nelse:\n    print("돈이 부족해요")')], [['>=', '왼쪽 값이 오른쪽 값보다 크거나 같은지 비교하는 기호'], ['if', '조건이 참일 때 들여쓴 코드를 실행하는 문법'], ['else', 'if 조건이 거짓일 때 실행할 부분'], ['들여쓰기', '코드가 어느 조건에 속하는지 표시하는 공백'], ['print()', '값을 화면에 보여 주는 함수']]),
  makeLesson(11, 4, '내일의 준비물 확인하기', '공책·연필·지우개 세 가지를 리스트로 출력하고, 준비물 하나를 더해 총 네 개임을 확인합니다.', 'challenge', 'supplies = ["공책", "연필", "지우개"]\nfor item in supplies:\n    print("준비물:", item)\nprint("준비물 개수:", len(supplies))', '준비물: 공책\n준비물: 연필\n준비물: 지우개\n준비물 개수: 3', { prompt: 'supplies 리스트에 좋아하는 준비물 1개를 추가하고 기존 항목과 새 항목이 출력되며 총 4개로 표시되게 하세요.', hint: '첫 줄 닫는 대괄호 앞에 `, "자"`처럼 쉼표와 새 문자열을 넣으세요. 예: `supplies = ["공책", "연필", "지우개", "자"]`. `for`와 `len()`은 그대로 두고 다시 실행해 네 줄과 개수 4를 확인하세요.', runtimeCheck: 'supplies', checks: [{ mode: 'changed', value: '', feedback: '새 준비물까지 목록과 개수를 확인했어요.' }] }, [{ type: 'explanation', title: '생활 속 질문', body: '내일 챙길 공책, 연필, 지우개를 목록으로 모아 둡니다. 좋아하는 준비물 하나를 추가하면 목록과 개수가 함께 바뀌어야 해요.' }, example('첫 줄 대괄호 안에 준비물 세 개를 리스트로 담아요. `for item in supplies:`는 리스트에서 item을 하나씩 꺼내요. 들여쓴 `print()`가 각 항목을 한 줄씩 보여 줘요. 마지막 `len(supplies)`는 리스트 안 항목 수를 세어 3을 보여 줘요. 도전에서 하나를 추가하면 4가 됩니다.', 'supplies = ["공책", "연필", "지우개"]\nfor item in supplies:\n    print("준비물:", item)\nprint("준비물 개수:", len(supplies))')], [['리스트', '여러 값을 순서대로 담는 자료 구조'], ['for', '묶음에서 값을 하나씩 꺼내 같은 코드를 반복하는 문법'], ['len()', '묶음이나 문자열의 길이를 세는 함수'], ['print()', '값을 화면에 보여 주는 함수']]),
  makeLesson(11, 5, '일주일 독서 기록', '월요일부터 일요일까지 읽은 쪽수를 기록하고 sum()으로 합계를 구합니다.', 'challenge', 'pages = [5, 0, 8, 4, 0, 10, 3]\nprint("총 독서 쪽수:", sum(pages))', '총 독서 쪽수: 30', challenge('7개 중 하루의 기록을 다른 0 이상 정수로 바꾸고 새 합계를 구하세요. 0은 읽지 않은 날이에요.', 'pages 리스트에서 숫자 하나만 바꾸세요. 예: 첫 숫자를 7로 바꾸면 `pages = [7, 0, 8, 4, 0, 10, 3]`이에요. 항목은 7개로 유지하고 `sum(pages)`는 그대로 둡니다.', 'reading', '일주일 기록의 실제 합계를 계산했어요.'), [{ type: 'explanation', title: '생활 속 질문', body: '월요일부터 일요일까지 읽은 쪽수를 기록해 일주일 합계를 알아봅니다. 0은 읽지 않은 날이고, 모든 기록은 0 이상 정수예요.' }, example('첫 줄 `pages` 리스트에는 일주일의 기록 7개가 순서대로 들어 있어요. `sum(pages)`는 리스트 숫자를 모두 더해요. `print()`는 계산한 합계를 보여 줘요. 시작 합계는 30쪽이고, 하루 숫자 하나를 바꾸면 실제 합계도 바뀌어야 해요.', 'pages = [5, 0, 8, 4, 0, 10, 3]\nprint("총 독서 쪽수:", sum(pages))')], [['리스트', '여러 값을 순서대로 담는 자료 구조'], ['sum()', '숫자 묶음의 합계를 구하는 함수'], ['정수', '소수점이 없는 수'], ['print()', '값을 화면에 보여 주는 함수']]),
  makeLesson(11, 6, '우리 반 간식 가격표', '간식 이름을 key로, 가격을 value로 저장한 딕셔너리에서 빵 가격을 찾아봅니다.', 'challenge', 'prices = {"우유": 1000, "빵": 1500}\nname = "빵"\nprint(f"{name} 가격: {prices[name]}원")', '빵 가격: 1500원', challenge('새 간식 이름과 양의 정수 가격을 하나 더 추가하고 그 이름표로 가격을 찾아 출력하세요.', '첫 줄 딕셔너리에 `, "과일": 1200`처럼 새 key와 value를 추가하고, 둘째 줄 name도 `"과일"`로 바꾸세요. 예: `prices["과일"] = 1200`을 첫 줄 다음에 추가해도 됩니다. 마지막 대괄호 조회는 같은 이름의 가격을 찾습니다.', 'price', '새 간식의 이름표로 실제 가격을 찾았어요.'), [{ type: 'explanation', title: '생활 속 질문', body: '우리 반 간식 가격표에서 이름으로 가격을 찾습니다. 우유와 빵 두 쌍을 먼저 저장하고, 새 간식 한 쌍을 직접 추가해 보세요.' }, example('첫 줄 딕셔너리에서 `"우유"`와 `"빵"`은 key(이름표), 1000과 1500은 value(가격)예요. 둘째 줄 `name = "빵"`은 찾을 이름을 정해요. 마지막 `prices[name]`은 그 key에 연결된 가격을 꺼내고, f-string이 이름과 원 단위를 한 줄로 보여 줘요.', 'prices = {"우유": 1000, "빵": 1500}\nname = "빵"\nprint(f"{name} 가격: {prices[name]}원")')], [['딕셔너리', 'key와 value를 짝으로 저장하는 자료 구조'], ['key', '딕셔너리에서 값을 찾는 이름표'], ['value', 'key에 연결되어 저장된 실제 값'], ['f-string', '문자열 안의 중괄호에 변수 값을 넣는 방법'], ['print()', '값을 화면에 보여 주는 함수']]),
  makeLesson(11, 7, '여기까지 해낸 나에게', '계산·조건·목록·이름표로 생활 문제를 해결한 과정을 돌아보고 학습을 마무리해요.', 'read', undefined, undefined, undefined, [{ type: 'explanation', title: '우리가 해낸 일', body: '시간과 돈을 계산하고, 조건에 따라 안내를 보여 주고, 준비물과 독서 기록을 목록으로 다뤘어요. 간식 이름으로 가격을 찾는 프로그램도 만들었어요.' }, { type: 'tip', title: '끝까지 차근차근', body: '처음에는 낯설었던 코드를 읽고 직접 바꾸고 결과를 확인하며 여기까지 왔어요. 모든 명령을 외우지 않아도 괜찮아요. 기억나지 않으면 핵심 용어와 예제를 다시 보고 한 줄씩 실행해 보면 돼요. 작은 문제를 스스로 해결해 본 경험이 다음 도전의 든든한 출발점이 될 거예요. 끝까지 해낸 여러분을 칭찬해요!' }], [['복습', '배운 내용을 다시 살펴보고 기억을 단단하게 만드는 일'], ['문제 해결', '생활 속 질문을 작은 단계와 코드로 풀어 가는 과정']]),
]);
