import { chapter, makeLesson } from './lessonFactory';

export const chapter5 = chapter(5, '기초', [
  makeLesson(5, 1, '주석', '숫자 기호 # 뒤의 글은 메모가 되어 실행되지 않습니다.', 'challenge', '# 오늘의 메모\nprint("주석은 설명을 도와줘요")', '주석은 설명을 도와줘요', { prompt: 'print()가 실행하는 결과는 유지하면서, 코드에 나만의 주석을 한 줄 추가하세요.', hint: 'print() 줄의 위나 아래에서 #로 시작하는 주석 줄을 찾거나 새로 만들어요. 메모 문장을 바꾼 뒤 다시 실행해 출력 결과는 그대로이고 코드에는 설명이 남는지 관찰하세요.', checks: [{ mode: 'contains', value: '주석', feedback: '메모와 실행 코드를 잘 구분했어요.' }] }),
  makeLesson(5, 2, '리터럴 상수와 숫자형', '코드에 직접 적은 10, 3.14 같은 값은 리터럴입니다. 정수와 실수를 구분해요.', 'challenge', 'apples = 3\nprice = 1200.0\nprint(apples)\nprint(price)', '3\n1200.0', { prompt: 'apples의 개수와 price의 가격을 나의 숫자로 바꾸고, 정수와 실수 출력이 어떻게 달라지는지 관찰하세요.', hint: 'apples =와 price = 줄의 숫자 리터럴을 찾으세요. 개수는 정수, 가격은 필요하면 소수로 바꾼 뒤 다시 실행해 두 출력 값이 바뀌는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '나만의 숫자 리터럴을 출력했어요.' }] }),
  makeLesson(5, 3, '문자열과 따옴표', '작은따옴표와 큰따옴표로 글자를 감싸면 문자열이 됩니다.', 'challenge', 'message = "파이썬은 재미있어요"\nprint(message)', '파이썬은 재미있어요', { prompt: 'message 변수의 문자열을 나만의 응원 문장으로 바꾸고, 출력 결과에 그 문장이 나타나는지 확인하세요.', hint: 'message = 줄의 따옴표 안 글자를 찾으세요. 따옴표는 남기고 문장만 바꾼 뒤 다시 실행해 출력 결과가 내 응원 문장으로 바뀌는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '나만의 문자열을 변수에 담았어요.' }] }),
  makeLesson(5, 4, '문자열 포매팅과 이스케이프', 'f-string과 \\n 같은 이스케이프 문자를 사용하면 출력 모양을 쉽게 만들 수 있습니다.', 'challenge', 'name = "민준"\nprint(f"안녕, {name}!")\nprint("첫 줄\\n둘째 줄")', '안녕, 민준!\n첫 줄\n둘째 줄', { prompt: 'name 변수의 이름을 바꾸어 f-string 인사가 새 이름을 보여 주게 하세요.', hint: 'name = 줄의 따옴표 안 이름을 찾으세요. 이름만 바꾼 뒤 다시 실행해 인사 줄은 달라지고 두 줄 출력은 그대로인지 관찰하세요.', checks: [{ mode: 'contains', value: '안녕', feedback: '문자열 포매팅을 사용했어요.' }, { mode: 'changed', value: '', feedback: '이름을 바꾸어 나만의 인사를 만들었어요.' }] }),
  makeLesson(5, 5, '변수와 식별자 이름', '변수는 값에 붙이는 이름표입니다. 이름은 역할이 드러나고 규칙에 맞아야 합니다.', 'challenge', 'student_name = "지우"\nscore = 95\nprint(student_name, score)', '지우 95', { prompt: 'student_name과 score에 나의 정보와 점수를 넣고, 두 변수의 역할이 출력에 드러나는지 확인하세요.', hint: 'student_name =와 score = 두 줄의 이름표 뒤 값을 찾으세요. 따옴표 안 이름과 숫자 점수를 바꾼 뒤 다시 실행해 출력 두 값이 함께 달라지는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '나의 변수 이름과 값으로 바꿨어요.' }] }),
  makeLesson(5, 6, '자료형과 객체', 'type()으로 값의 종류를 살펴봅니다. 숫자와 문자열은 서로 다른 자료형입니다.', 'challenge', 'print(type(7).__name__)\nprint(type("seven").__name__)', 'int\nstr', { prompt: '기존 두 줄 아래에 실수 또는 참·거짓 값의 자료형을 확인하는 코드를 추가하세요.', hint: '두 print(type(...)) 줄에서 괄호 안 값이 들어가는 위치를 찾으세요. type(3.14) 또는 type(True)를 한 줄 추가한 뒤 다시 실행해 float 또는 bool이 출력되는지 관찰하세요.', checks: [{ mode: 'regex', value: '(?:^|\\n)(?:float|bool)(?:$|\\n)', feedback: '실수 또는 참·거짓 자료형을 직접 확인했어요.' }] }),
  makeLesson(5, 7, '프로그램 작성과 들여쓰기', '콜론 뒤 블록은 같은 칸만큼 들여써야 합니다. 공백은 코드의 구조를 보여 줍니다.', 'challenge', 'ready = True\nif ready:\n    print("시작!")', '시작!', { prompt: 'if 블록의 들여쓰기는 유지하고, 시작 메시지만 나만의 문장으로 바꾸세요.', hint: 'if ready: 다음 줄의 들여쓴 print()와 따옴표 안 문장을 찾으세요. 따옴표 안 문장만 바꾼 뒤 다시 실행해 조건이 참일 때 새 메시지가 출력되는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '조건 블록의 들여쓰기를 지키며 메시지를 바꿨어요.' }] }),
  makeLesson(5, 8, '기초 확인 실습', '주석·변수·문자열·숫자를 한 프로그램 안에서 연결해 봅니다.', 'challenge', '# 오늘의 기록\nname = "지우"\ndays = 5\nprint(name, "는", days, "일째 연습 중")', '지우 는 5 일째 연습 중', { prompt: 'name과 days를 나의 이름과 연습 일수로 바꾸고, 기록 문장이 새 값으로 출력되게 하세요.', hint: 'name =와 days = 두 변수 줄의 값을 찾으세요. 이름은 문자열, 일수는 정수로 바꾼 뒤 다시 실행해 두 값이 기록 문장에 반영되는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '나의 이름과 연습 날짜를 기록했어요.' }] }),
]);
