import { chapter, makeLesson } from './lessonFactory';

export const chapter8 = chapter(8, '함수', [
  makeLesson(8, 1, '함수와 매개변수', 'def로 자주 쓸 동작을 묶고 매개변수로 재료를 받습니다.', 'challenge', 'def greet(name):\n    print("안녕,", name)\n\ngreet("민준")', '안녕, 민준', { prompt: 'greet 호출의 괄호 안 이름을 바꾸고, 매개변수로 전달한 이름이 출력되는지 확인하세요.', hint: '코드 아래쪽 greet("민준")에서 괄호 안 문자열을 찾으세요. 그 이름만 바꾼 뒤 다시 실행해 인사 결과에도 새 이름이 나타나는지 관찰하세요.', sourcePatterns: ['def\\s+greet', 'name', 'greet\\s*\\('], checks: [{ mode: 'contains', value: '안녕', feedback: '함수에 입력을 전달했어요.' }, { mode: 'changed', value: '', feedback: '다른 이름을 함수에 전달했어요.' }] }),
  makeLesson(8, 2, '지역 변수', '함수 안에서 만든 변수는 그 함수 안에서 주로 사용됩니다. 먼저 함수 안에서 값을 만들어 바로 출력해 봅니다.', 'challenge', 'def make_message():\n    message = "함수 안의 메시지"\n    print(message)\n\nmake_message()', '함수 안의 메시지', { prompt: 'message가 출력할 문장을 바꾸고, 함수 호출 결과가 새 문장으로 나오는지 확인하세요.', hint: '함수 안 message = 줄의 따옴표 안 문장을 찾으세요. 문장만 바꾼 뒤 다시 실행해 make_message()의 결과가 달라지는지 관찰하세요.', sourcePatterns: ['def\\s+make_message', 'message', 'print\\s*\\('], checks: [{ mode: 'changed', value: '', feedback: '함수 안 지역 변수의 값을 바꾸었어요.' }] }),
  makeLesson(8, 3, 'global 더 알아보기', '함수 안에서 바깥 변수의 값을 직접 바꾸는 global이라는 방법이 있어요. 처음에는 매개변수와 return으로 값을 주고받는 흐름을 먼저 익히고, 궁금할 때만 짧은 예를 읽어 보세요.', 'optional'),
  makeLesson(8, 4, '기본 인수', '매개변수에 기본값을 정하면 입력을 생략해도 함수가 동작합니다.', 'challenge', 'def cheer(name="친구"):\n    print(name, "힘내!")\n\ncheer()\ncheer("지우")', '친구 힘내!\n지우 힘내!', { prompt: 'cheer 함수의 기본 이름을 바꾸고, 값을 생략한 호출의 결과가 달라지는지 확인하세요.', hint: 'def cheer(name="친구"): 줄의 기본값 문자열을 찾으세요. 이름만 바꾼 뒤 다시 실행해 cheer() 줄은 새 이름, cheer("지우") 줄은 지우로 남는지 관찰하세요.', sourcePatterns: ['def\\s+cheer', 'name', 'cheer\\s*\\('], checks: [{ mode: 'contains', value: '힘내', feedback: '기본 인수를 사용했어요.' }, { mode: 'changed', value: '', feedback: '기본 인수를 나만의 이름으로 바꿨어요.' }] }),
  makeLesson(8, 5, '키워드 인수', '매개변수 이름을 함께 적으면 순서를 헷갈리지 않고 값을 전달할 수 있습니다.', 'challenge', 'def profile(name, grade):\n    print(name, grade, "학년")\n\nprofile(grade=2, name="민준")', '민준 2 학년', { prompt: 'profile 호출의 name과 grade 키워드 값을 나에게 맞게 바꾸고 결과를 확인하세요.', hint: 'profile(grade=2, name="민준") 괄호 안의 두 키워드 값을 찾으세요. 이름과 학년 숫자를 바꾼 뒤 다시 실행해 키워드 이름에 맞는 순서로 출력되는지 관찰하세요.', sourcePatterns: ['def\\s+profile', 'name', 'grade', 'profile\\s*\\(', '='], checks: [{ mode: 'contains', value: '학년', feedback: '키워드로 값을 전달했어요.' }, { mode: 'changed', value: '', feedback: '나에게 맞는 키워드 인수 값을 전달했어요.' }] }),
  makeLesson(8, 6, '가변 인수 더 알아보기', '가변 인수는 함수가 여러 값을 한 번에 받을 때 쓰는 방법이에요. 필수 흐름을 마친 뒤 궁금할 때 짧은 예를 읽어 보세요.', 'optional'),
  makeLesson(8, 7, 'return', 'return은 함수의 계산 결과를 호출한 곳으로 돌려줍니다.', 'challenge', 'def average(a, b):\n    return (a + b) / 2\n\nprint("평균:", average(80, 90))', '평균: 85.0', { prompt: 'average 호출에 다른 두 점수를 넣고, return이 계산한 평균을 확인하세요.', hint: 'print() 안 average(80, 90) 호출의 두 숫자를 찾으세요. 두 점수를 바꾼 뒤 다시 실행해 평균 출력 값도 달라지는지 관찰하세요.', sourcePatterns: ['def\\s+average', 'return', 'average\\s*\\(', '평균'], checks: [{ mode: 'contains', value: '평균', feedback: 'return 결과를 사용했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 점수의 평균을 계산했어요.' }] }),
  makeLesson(8, 8, '문서 문자열', '함수 첫 줄의 설명 문자열은 함수의 목적을 알려 주는 작은 안내문입니다.', 'challenge', 'def square(number):\n    """숫자를 제곱해 돌려줘요."""\n    return number ** 2\n\nprint(square(4))', '16', { prompt: 'square에 넣을 숫자를 바꾸고, 제곱 결과가 달라지는지 확인하세요. 함수 안의 설명 문자열도 읽어 보세요.', hint: 'print(square(4))의 숫자 4를 찾아 다른 수로 바꿔요. 따옴표 세 개로 감싼 문장은 함수 설명이므로 그대로 두고 다시 실행해 제곱 결과가 달라지는지 관찰하세요.', sourcePatterns: ['def\\s+square', '"""', 'return', '\\*\\*', 'print\\s*\\('], checks: [{ mode: 'changed', value: '', feedback: '함수 설명을 읽고 바꾼 숫자의 제곱 결과를 확인했어요.' }] }),
  makeLesson(8, 9, '함수 확인 실습', '할인 가격 함수를 만들며 입력·처리·결과의 흐름을 정리합니다.', 'challenge', 'def discount(price, rate):\n    return price * (1 - rate / 100)\n\nprint("할인 가격:", int(discount(10000, 20)))', '할인 가격: 8000', { prompt: 'discount 호출의 가격이나 할인율을 바꾸고, 함수가 새 할인 가격을 계산하는지 확인하세요.', hint: 'print() 안 discount(10000, 20) 호출의 두 숫자를 찾으세요. 가격 또는 할인율을 바꾼 뒤 다시 실행해 할인 가격 출력이 달라지는지 관찰하세요.', sourcePatterns: ['def\\s+discount', 'return', 'discount\\s*\\(', '할인 가격'], checks: [{ mode: 'contains', value: '할인 가격', feedback: '함수로 계산을 재사용했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 가격과 할인율로 다시 계산했어요.' }] }),
]);
