import { chapter, makeLesson } from './lessonFactory';

export const chapter9 = chapter(9, '모듈', [
  makeLesson(9, 1, 'import와 코드 묶음', 'import는 다른 파일이나 표준 라이브러리의 도구를 가져오는 명령입니다. math 모듈에는 math.sqrt(x)와 math.fabs(x) 같은 계산 도구가 있어요.', 'challenge', 'import math\nprint(math.sqrt(25))\nprint(math.fabs(-3.5))', '5.0\n3.5', { prompt: 'import math는 그대로 두고, math의 계산 도구에 넣는 수를 바꾸어 제곱근이나 절대값 결과를 확인하세요.', hint: 'print() 안의 math.sqrt(25) 또는 math.fabs(-3.5)에서 괄호 안 숫자를 찾아 바꿔 보세요. 다시 실행해 제곱근은 새로운 값, 절대값은 0에서 떨어진 거리로 나타나는지 관찰하세요.', sourcePatterns: ['import\\s+math', 'math\\.', 'print\\s*\\('], checks: [{ mode: 'changed', value: '', feedback: '모듈의 계산 도구로 새로운 결과를 확인했어요.' }] }),
  makeLesson(9, 2, 'from ... import', '모듈 이름을 매번 쓰기 싫을 때 필요한 이름만 가져올 수 있습니다.', 'challenge', 'from math import pi\nprint(round(pi, 2))', '3.14', { prompt: 'round()의 자릿수를 바꾸어 pi 값을 다른 소수 자리까지 출력하세요.', hint: 'round(number, ndigits)는 첫 번째 숫자를 두 번째 숫자만큼 소수점 아래 자릿수로 반올림해 정리해요. print(round(pi, 2))에서 두 번째 숫자 2를 찾아 1이나 3처럼 바꾼 뒤 다시 실행해 pi 출력 자릿수가 달라지는지 관찰하세요.', sourcePatterns: ['from\\s+math\\s+import\\s+pi', 'round\\s*\\('], checks: [{ mode: 'changed', value: '', feedback: '원하는 자릿수로 모듈 값을 출력했어요.' }] }),
  makeLesson(9, 3, '__name__ 참고', '모듈에도 이름표가 있다는 것을 알아보는 선택 참고예요. 파일을 직접 실행할 때와 다른 코드에서 가져다 쓸 때를 구분하는 약속이지만, 이 브라우저 수업에서는 자세히 다루지 않아요.', 'optional'),
  makeLesson(9, 4, '브라우저에서 모듈 살펴보기', '이 실습에서는 브라우저에서 바로 쓸 수 있도록 준비된 표준 모듈을 사용합니다. 모듈을 기능별 도구 상자로 나누면 코드를 읽기 쉬워집니다.', 'read'),
  makeLesson(9, 5, 'dir()로 살펴보기', 'dir()은 모듈이나 객체에서 사용할 수 있는 이름을 살펴보는 데 도움을 줍니다.', 'challenge', 'import math\nprint("sqrt" in dir(math))', 'True', { prompt: 'dir(math) 안에 pi 이름도 있는지 확인하도록 코드를 바꾸세요.', hint: 'print() 안의 "sqrt" 문자열을 찾으세요. 문자열을 "pi"로 바꾼 뒤 다시 실행해 True가 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: 'True', feedback: 'dir()로 모듈의 이름을 찾아봤어요.' }] }),
  makeLesson(9, 7, '모듈 확인 실습', '필요한 기능을 모듈에서 가져와 원의 넓이를 계산합니다.', 'challenge', 'import math\nradius = 3\narea = math.pi * radius ** 2\nprint("원의 넓이:", round(area, 2))', '원의 넓이: 28.27', { prompt: 'radius를 다른 반지름으로 바꾸고, math.pi를 사용한 원의 넓이가 새 값으로 나오는지 관찰하세요.', hint: 'radius = 3 줄의 숫자를 찾으세요. 숫자를 5처럼 바꾼 뒤 다시 실행해 원의 넓이 출력이 커지는지 관찰하세요.', sourcePatterns: ['import\\s+math', 'radius', 'math\\.pi', '원의 넓이'], checks: [{ mode: 'contains', value: '원의 넓이', feedback: 'math 모듈을 사용해 계산했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 반지름으로 원의 넓이를 다시 계산했어요.' }] }),
]);
