import { chapter, makeLesson } from './lessonFactory';

export const chapter9 = chapter(9, '모듈', [
  makeLesson(9, 1, 'import와 코드 묶음', 'import는 다른 파일이나 표준 라이브러리의 도구를 가져오는 명령입니다. math 모듈에는 math.sqrt(x)와 math.fabs(x) 같은 계산 도구가 있어요.', 'challenge', 'import math\nprint(round(math.sqrt(25)))', '5', { prompt: 'import math는 그대로 두고, math의 다른 계산 도구를 사용해 제곱근이나 절대값 결과를 바꾸어 확인하세요.', hint: 'print() 안의 math.sqrt(25) 호출 괄호와 숫자를 찾으세요. math.fabs(-3.5) 같은 도구로 식을 바꾼 뒤 다시 실행해 출력 결과가 어떻게 달라지는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '모듈의 다른 도구로 계산했어요.' }] }),
  makeLesson(9, 2, 'from ... import', '모듈 이름을 매번 쓰기 싫을 때 필요한 이름만 가져올 수 있습니다.', 'challenge', 'from math import pi\nprint(round(pi, 2))', '3.14', { prompt: 'round()의 자릿수를 바꾸어 pi 값을 다른 소수 자리까지 출력하세요.', hint: 'round(number, ndigits)는 첫 번째 숫자를 두 번째 숫자만큼 소수점 아래 자릿수로 반올림해 정리해요. print(round(pi, 2))에서 두 번째 숫자 2를 찾아 원하는 자릿수로 바꾼 뒤 다시 실행해 pi 출력이 어떻게 달라지는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '원하는 자릿수로 모듈 값을 출력했어요.' }] }),
  makeLesson(9, 3, '__name__ 살펴보기', '파일이 직접 실행되는지 다른 코드에서 불린 것인지 구분할 때 __name__을 사용합니다.', 'challenge', 'if __name__ == "__main__":\n    print("이 파일을 직접 실행했어요")', '이 파일을 직접 실행했어요', { prompt: '__name__ 조건은 유지하고, 직접 실행 안내 문장만 나만의 말로 바꾸세요.', hint: '조건문 안쪽 들여쓴 print()의 따옴표 안 문장을 찾으세요. 문장만 바꾼 뒤 다시 실행해 __name__ 조건 아래 새 안내가 출력되는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '__name__ 조건 안의 안내 문장을 바꿨어요.' }] }),
  makeLesson(9, 4, '브라우저에서 모듈 살펴보기', '이 실습에서는 브라우저에서 바로 쓸 수 있도록 준비된 표준 모듈을 사용합니다. 모듈을 기능별 도구 상자로 나누면 코드를 읽기 쉬워집니다.', 'read'),
  makeLesson(9, 5, 'dir()로 살펴보기', 'dir()은 모듈이나 객체에서 사용할 수 있는 이름을 살펴보는 데 도움을 줍니다.', 'challenge', 'import math\nprint("sqrt" in dir(math))', 'True', { prompt: 'dir(math) 안에 pi 이름도 있는지 확인하도록 코드를 바꾸세요.', hint: 'print() 안의 "sqrt" 문자열을 찾으세요. 문자열을 "pi"로 바꾼 뒤 다시 실행해 True가 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: 'True', feedback: 'dir()로 모듈의 이름을 찾아봤어요.' }] }),
  makeLesson(9, 6, '패키지와 모듈 정리', '여러 모듈을 폴더로 묶은 것이 패키지입니다. 기능별로 나누면 큰 프로그램도 읽기 쉬워집니다.', 'challenge', 'import math\nprint("도구 상자:", math.__name__)', '도구 상자: math', { prompt: 'math 대신 다른 표준 모듈을 import하고, 모듈 이름이 출력되는지 확인하세요.', hint: 'import math 줄의 모듈 이름과 아래 math.__name__ 부분을 찾으세요. 두 곳을 같은 표준 모듈 이름으로 바꾼 뒤 다시 실행해 도구 상자 뒤 이름이 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: '도구 상자', feedback: '모듈을 도구 상자로 이해했어요.' }, { mode: 'changed', value: '', feedback: '다른 표준 모듈의 이름을 출력했어요.' }] }),
  makeLesson(9, 7, '모듈 확인 실습', '필요한 기능을 모듈에서 가져와 원의 넓이를 계산합니다.', 'challenge', 'import math\nradius = 3\narea = math.pi * radius ** 2\nprint("원의 넓이:", round(area, 2))', '원의 넓이: 28.27', { prompt: 'radius를 다른 반지름으로 바꾸고, math.pi를 사용한 원의 넓이가 새 값으로 나오는지 관찰하세요.', hint: 'radius = 3 줄의 숫자를 찾으세요. 숫자를 5처럼 바꾼 뒤 다시 실행해 원의 넓이 출력이 커지는지 관찰하세요.', checks: [{ mode: 'contains', value: '원의 넓이', feedback: 'math 모듈을 사용해 계산했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 반지름으로 원의 넓이를 다시 계산했어요.' }] }),
]);
