import { chapter, makeLesson } from './lessonFactory';

export const chapter10 = chapter(10, '자료 구조', [
  makeLesson(10, 1, '리스트', '리스트는 순서가 있는 여러 값을 한 번에 담는 상자입니다.', 'challenge', 'colors = ["빨강", "초록", "파랑"]\nprint(colors[0])\nprint(len(colors))', '빨강\n3', { prompt: 'colors 리스트에 좋아하는 색을 하나 추가하고, 리스트의 길이가 4가 되는지 확인하세요.', hint: 'colors = 리스트 줄의 닫는 대괄호 뒤나 print() 앞을 찾으세요. colors.append("노랑")처럼 항목을 추가한 뒤 다시 실행해 길이 4와 새 목록 상태를 관찰하세요.', checks: [{ mode: 'contains', value: '4', feedback: '리스트의 크기가 늘었어요.' }, { mode: 'changed', value: '', feedback: '좋아하는 색을 추가해 리스트 크기가 늘었어요.' }] }),
  makeLesson(10, 2, '객체와 클래스 맛보기', '클래스는 비슷한 객체를 만들 설계도입니다. 지금은 객체가 값과 기능을 함께 가질 수 있다는 점만 기억해요.', 'read'),
  makeLesson(10, 3, '튜플', '튜플은 여러 값을 순서대로 담지만 만든 뒤 내용을 바꾸지 않는 묶음입니다.', 'challenge', 'point = (3, 5)\nprint("x:", point[0])\nprint("y:", point[1])', 'x: 3\ny: 5', { prompt: 'point 튜플의 두 좌표를 다른 값으로 바꾸고, x와 y 출력이 함께 달라지는지 확인하세요.', hint: 'point = (3, 5) 줄의 괄호 안 두 숫자를 찾으세요. 두 숫자 중 하나 이상을 바꾼 뒤 다시 실행해 point[0], point[1]의 위치별 결과가 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: 'x:', feedback: '튜플의 위치별 값을 꺼냈어요.' }, { mode: 'changed', value: '', feedback: '바꾼 좌표의 위치별 값을 꺼냈어요.' }] }),
  makeLesson(10, 4, '딕셔너리', '딕셔너리는 key와 value를 짝으로 저장해 이름표로 값을 찾습니다.', 'challenge', 'scores = {"수학": 90, "과학": 85}\nfor subject, score in scores.items():\n    print(subject, score)', '수학 90\n과학 85', { prompt: 'scores 딕셔너리에 좋아하는 과목과 점수 한 쌍을 추가하고, 순회 결과에 새 줄이 나타나게 하세요.', hint: 'scores = 딕셔너리의 마지막 항목 뒤를 찾으세요. 쉼표와 "과목": 점수 쌍을 추가한 뒤 다시 실행해 새 과목과 점수가 한 줄 출력되는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '새 과목과 점수를 한 줄 추가했어요.' }] }),
  makeLesson(10, 5, '시퀀스와 순회', 'for 문으로 리스트의 항목을 하나씩 꺼내면 목록 전체를 다룰 수 있습니다.', 'challenge', 'todos = ["수학 숙제", "물 마시기"]\nfor todo in todos:\n    print("할 일:", todo)', '할 일: 수학 숙제\n할 일: 물 마시기', { prompt: 'todos 리스트에 할 일을 하나 더 추가하고, for 루프가 새 항목도 출력하는지 확인하세요.', hint: 'todos = 리스트의 닫는 대괄호 앞을 찾으세요. 쉼표와 새 할 일 문자열을 추가한 뒤 다시 실행해 “할 일:” 줄이 하나 더 나오는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '새 할 일을 추가하고 목록을 순회했어요.' }] }),
  makeLesson(10, 6, '집합', '집합은 중복을 없애고 값이 있는지 빠르게 확인하는 자료 구조입니다.', 'challenge', 'tags = {"python", "coding", "python"}\nprint(len(tags))\nprint("coding" in tags)', '2\nTrue', { prompt: 'tags 집합에 기존과 다른 새 태그를 추가해 집합 길이가 3이 되게 하세요.', hint: 'tags = 집합 줄의 닫는 중괄호 뒤나 다음 print() 앞을 찾으세요. tags.add("새태그")를 넣고 다시 실행해 중복 없이 길이 3과 True가 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: '3\nTrue', feedback: '새 태그를 추가해 집합의 크기가 늘었어요.' }] }),
  makeLesson(10, 7, '참조', '변수는 값이 있는 곳을 가리킬 수 있어, 같은 리스트를 함께 바꾸는 일이 생깁니다.', 'challenge', 'first = ["연필"]\nsecond = first\nsecond.append("지우개")\nfor item in first:\n    print(item)', '연필\n지우개', { prompt: 'second가 가리키는 리스트에 준비물을 하나 더 추가하고, first 출력에도 새 항목이 나타나는지 확인하세요.', hint: 'second.append("지우개") 줄 아래를 찾으세요. 같은 모양의 second.append("새 준비물") 줄을 하나 더 적은 뒤 다시 실행해 first의 출력에도 항목이 늘어나는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '같은 리스트에 새 준비물을 추가했어요.' }] }),
  makeLesson(10, 8, '문자열 더 알아보기', '문자열도 순서가 있는 시퀀스라 인덱스, len(), upper() 등을 사용할 수 있습니다.', 'challenge', 'word = "python"\nprint(word[0])\nprint(word.upper())\nprint(len(word))', 'p\nPYTHON\n6', { prompt: 'word를 다른 영어 단어로 바꾸고, 첫 글자·대문자·길이 결과가 달라지는지 관찰하세요.', hint: 'word = 줄의 따옴표 안 python을 찾으세요. 길이를 확인할 수 있는 다른 영어 단어로 바꾼 뒤 다시 실행해 세 출력이 새 단어에 맞게 바뀌는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '다른 문자열의 여러 기능을 사용했어요.' }] }),
  makeLesson(10, 9, '자료 구조 확인 실습', '리스트와 딕셔너리를 함께 순회해 과목별 점수를 출력합니다.', 'challenge', 'scores = {"수학": 90, "과학": 85, "미술": 95}\nfor subject, score in scores.items():\n    print(subject, score, "점")', '수학 90 점\n과학 85 점\n미술 95 점', { prompt: 'scores 딕셔너리에 좋아하는 과목과 점수를 추가하고, for 순회 결과에 새 과목이 출력되게 하세요.', hint: 'scores = 딕셔너리의 마지막 항목 뒤를 찾으세요. 새 "과목": 점수 쌍을 추가한 뒤 다시 실행해 과목과 점이 붙은 새 줄이 나오는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '새 과목을 추가하고 자료 구조를 순회했어요.' }] }),
]);
