import { chapter, makeLesson } from './lessonFactory';

export const chapter6 = chapter(6, '연산자와 수식', [
  makeLesson(6, 1, '연산자', '더하기·빼기·곱하기·나누기와 나머지를 기호로 표현합니다.', 'challenge', 'a = 17\nb = 5\nprint(a // b)\nprint(a % b)', '3\n2', { prompt: 'a와 b를 다른 정수로 바꾸고, //가 구한 몫과 %가 구한 나머지가 어떻게 달라지는지 관찰하세요.', hint: 'a =와 b = 두 변수 줄의 숫자를 찾으세요. 두 정수를 바꾼 뒤 다시 실행해 아래 두 출력 줄의 몫과 나머지를 비교하세요.', checks: [{ mode: 'changed', value: '', feedback: '바꾼 두 수의 몫과 나머지를 관찰했어요.' }] }),
  makeLesson(6, 2, '연산 및 할당 연산자', '계산한 결과를 변수에 다시 저장할 때 +=, -= 같은 할당 연산자를 쓸 수 있습니다.', 'challenge', 'score = 10\nscore += 5\nscore -= 2\nprint(score)', '13', { prompt: 'score에 더하거나 빼는 숫자를 바꾸고, 최종 점수가 어떻게 갱신되는지 확인하세요.', hint: 'score += 5와 score -= 2 줄의 오른쪽 숫자를 찾으세요. 한 숫자를 바꾼 뒤 다시 실행해 마지막 print(score)의 값이 달라지는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '값을 계산하며 갱신했어요.' }] }),
  makeLesson(6, 3, '연산 순서', '곱셈과 나눗셈이 덧셈보다 먼저 계산됩니다. 순서를 모르면 괄호로 분명히 해요.', 'challenge', 'answer = 2 + 3 * 4\nprint(answer)', '14', { prompt: 'answer 수식의 덧셈을 괄호로 묶어 계산 결과를 20으로 만들어 보세요.', hint: 'answer = 2 + 3 * 4 줄에서 먼저 계산할 덧셈의 양쪽을 찾으세요. (2 + 3)처럼 괄호를 넣고 다시 실행해 answer가 20으로 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: '20', feedback: '괄호로 계산 순서를 바꿨어요.' }] }),
  makeLesson(6, 4, '수식 예제', '간식 가격과 개수로 예산을 계산해 실제 문제에 수식을 적용합니다.', 'challenge', 'price = 1200\ncount = 3\nbudget = 5000\nspent = price * count\nprint("사용 금액:", spent)\nprint("남은 금액:", budget - spent)', '사용 금액: 3600\n남은 금액: 1400', { prompt: 'price, count, budget 중 하나를 바꾸어 남은 금액이 새 값으로 계산되는지 확인하세요.', hint: 'price =, count =, budget = 변수 줄 중 바꿀 줄을 찾으세요. 숫자 하나만 바꾼 뒤 다시 실행해 사용 금액과 남은 금액이 함께 어떻게 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: '남은 금액', feedback: '예산 계산 결과를 확인했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 값으로 예산을 다시 계산했어요.' }] }),
  makeLesson(6, 5, '연산 확인 문제', '수식을 읽고 결과를 예상한 뒤 실행 결과로 확인합니다.', 'challenge', 'width = 8\nheight = 5\nprint("넓이:", width * height)\nprint("둘레:", (width + height) * 2)', '넓이: 40\n둘레: 26', { prompt: 'width와 height를 다른 가로·세로 길이로 바꾸고, 넓이와 둘레를 다시 계산하세요.', hint: 'width =와 height = 두 변수 줄의 숫자를 찾으세요. 두 길이 중 하나를 바꾼 뒤 다시 실행해 넓이와 둘레 출력이 모두 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: '넓이', feedback: '수식과 결과를 연결했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 가로와 세로로 다시 계산했어요.' }] }),
]);
