import { chapter, makeLesson } from './lessonFactory';

export const chapter10 = chapter(10, '자료 구조', [
  makeLesson(10, 1, '리스트', '리스트는 순서가 있는 여러 값을 한 번에 담는 상자입니다.', 'challenge', 'colors = ["빨강", "초록", "파랑"]\nprint(colors[0])\nprint(len(colors))', '빨강\n3', { prompt: '리스트에 좋아하는 색을 하나 더 넣으세요.', hint: 'append()를 사용해 보세요.', checks: [{ mode: 'contains', value: '4', feedback: '리스트의 크기가 늘었어요.' }] }),
  makeLesson(10, 2, '객체와 클래스 맛보기', '클래스는 비슷한 객체를 만들 설계도입니다. 지금은 객체가 값과 기능을 함께 가질 수 있다는 점만 기억해요.', 'read'),
  makeLesson(10, 3, '튜플', '튜플은 여러 값을 순서대로 담지만 만든 뒤 내용을 바꾸지 않는 묶음입니다.', 'challenge', 'point = (3, 5)\nprint("x:", point[0])\nprint("y:", point[1])', 'x: 3\ny: 5', { prompt: '좌표를 다른 값으로 바꿔 보세요.', hint: '튜플 안의 두 숫자를 고쳐요.', checks: [{ mode: 'contains', value: 'x:', feedback: '튜플의 위치별 값을 꺼냈어요.' }] }),
  makeLesson(10, 4, '딕셔너리', '딕셔너리는 key와 value를 짝으로 저장해 이름표로 값을 찾습니다.', 'challenge', 'scores = {"수학": 90, "과학": 85}\nprint(scores["수학"])', '90', { prompt: '좋아하는 과목과 점수를 하나 추가하세요.', hint: '딕셔너리에 "체육": 100 같은 항목을 넣어요.', checks: [{ mode: 'equals', value: '100', feedback: 'key로 value를 찾았어요.' }] }),
  makeLesson(10, 5, '시퀀스와 순회', 'for 문으로 리스트의 항목을 하나씩 꺼내면 목록 전체를 다룰 수 있습니다.', 'challenge', 'todos = ["수학 숙제", "물 마시기"]\nfor todo in todos:\n    print("할 일:", todo)', '할 일: 수학 숙제\n할 일: 물 마시기', { prompt: '할 일을 하나 더 추가해 출력하세요.', hint: 'todos 리스트에 문자열을 추가해요.', checks: [{ mode: 'contains', value: '할 일:', feedback: '목록을 순회했어요.' }] }),
  makeLesson(10, 6, '집합', '집합은 중복을 없애고 값이 있는지 빠르게 확인하는 자료 구조입니다.', 'challenge', 'tags = {"python", "coding", "python"}\nprint(len(tags))\nprint("coding" in tags)', '2\nTrue', { prompt: '새 태그를 하나 추가하세요.', hint: 'add()로 문자열을 넣어 보세요.', checks: [{ mode: 'equals', value: '2\nTrue', feedback: '집합의 중복 제거와 포함 검사를 확인했어요.' }] }),
  makeLesson(10, 7, '참조', '변수는 값이 있는 곳을 가리킬 수 있어, 같은 리스트를 함께 바꾸는 일이 생깁니다.', 'challenge', 'first = ["연필"]\nsecond = first\nsecond.append("지우개")\nprint(first)', '[\'연필\', \'지우개\']', { prompt: '리스트에 준비물을 하나 더 추가하세요.', hint: 'second에 append를 한 줄 더 적어 보세요.', checks: [{ mode: 'contains', value: '지우개', feedback: '두 이름이 같은 리스트를 가리킴을 확인했어요.' }] }),
  makeLesson(10, 8, '문자열 더 알아보기', '문자열도 순서가 있는 시퀀스라 인덱스, len(), upper() 등을 사용할 수 있습니다.', 'challenge', 'word = "python"\nprint(word[0])\nprint(word.upper())\nprint(len(word))', 'p\nPYTHON\n6', { prompt: '문자열을 다른 단어로 바꾸어 관찰하세요.', hint: 'word의 값을 영어 단어로 바꿔요.', checks: [{ mode: 'contains', value: 'P', feedback: '문자열의 여러 기능을 사용했어요.' }] }),
  makeLesson(10, 9, '자료 구조 확인 실습', '리스트와 딕셔너리를 함께 순회해 과목별 점수를 출력합니다.', 'challenge', 'scores = {"수학": 90, "과학": 85, "미술": 95}\nfor subject, score in scores.items():\n    print(subject, score, "점")', '수학 90 점\n과학 85 점\n미술 95 점', { prompt: '좋아하는 과목을 하나 더 추가하고 출력하세요.', hint: '딕셔너리에 새 항목을 추가해요.', checks: [{ mode: 'contains', value: '점', feedback: '자료 구조를 순회하며 값을 읽었어요.' }] }),
]);
