import { chapter, makeLesson } from './lessonFactory';

export const chapter7 = chapter(7, '흐름 제어', [
  makeLesson(7, 1, 'if 문', '조건이 참인지 확인하고 상황에 맞는 코드를 선택합니다.', 'challenge', 'temperature = 24\nif temperature >= 20:\n    print("따뜻해요")', '따뜻해요', { prompt: '온도를 바꾸어 다른 메시지도 확인하세요.', hint: '조건의 기준 숫자를 살펴보세요.', checks: [{ mode: 'contains', value: '따뜻', feedback: 'if 조건을 통과했어요.' }] }),
  makeLesson(7, 2, 'while 문', '조건이 참인 동안 같은 코드를 반복합니다. 반복이 끝나는 변화도 꼭 넣어요.', 'challenge', 'count = 1\nwhile count <= 3:\n    print("연습", count)\n    count += 1', '연습 1\n연습 2\n연습 3', { prompt: '반복 횟수를 5번으로 바꾸세요.', hint: 'while의 기준 숫자를 고쳐요.', checks: [{ mode: 'contains', value: '연습 5', feedback: 'while 반복을 안전하게 끝냈어요.' }] }),
  makeLesson(7, 3, 'for 루프', '목록이나 range의 값을 하나씩 꺼내 같은 작업을 반복합니다.', 'challenge', 'for number in range(1, 6):\n    print(number)', '1\n2\n3\n4\n5', { prompt: '1부터 10까지 출력하도록 바꾸세요.', hint: 'range의 끝 숫자는 포함되지 않아요.', checks: [{ mode: 'contains', value: '10', feedback: 'for 루프로 범위를 순회했어요.' }] }),
  makeLesson(7, 4, 'break 문', 'break는 반복을 즉시 멈춥니다. 원하는 대상을 찾았을 때 유용합니다.', 'challenge', 'for number in range(1, 10):\n    if number == 4:\n        print("찾았어요", number)\n        break', '찾았어요 4', { prompt: '멈출 숫자를 7로 바꾸세요.', hint: 'if 비교 숫자와 출력 숫자를 함께 고쳐요.', checks: [{ mode: 'contains', value: '7', feedback: 'break 시점을 바꿨어요.' }] }),
  makeLesson(7, 5, 'continue 문', 'continue는 현재 반복만 건너뛰고 다음 반복으로 이동합니다.', 'challenge', 'for number in range(1, 6):\n    if number == 3:\n        continue\n    print(number)', '1\n2\n4\n5', { prompt: '건너뛸 숫자를 4로 바꾸세요.', hint: 'continue 앞의 비교 숫자를 바꿔요.', checks: [{ mode: 'contains', value: '3', feedback: '반복 한 번을 건너뛰었어요.' }] }),
  makeLesson(7, 6, '흐름 제어 실습', '조건과 반복을 함께 사용해 짝수만 골라 출력합니다.', 'challenge', 'for number in range(1, 11):\n    if number % 2 == 0:\n        print(number, "은 짝수")', '2 은 짝수\n4 은 짝수\n6 은 짝수\n8 은 짝수\n10 은 짝수', { prompt: '1부터 30까지 중 3의 배수만 출력해 보세요.', hint: 'number % 3 == 0인지 확인하면 됩니다.', checks: [{ mode: 'contains', value: '30', feedback: '조건과 반복으로 여러 값을 골랐어요.' }] }),
]);
