import { chapter, makeLesson } from './lessonFactory';

export const chapter7 = chapter(7, '흐름 제어', [
  makeLesson(7, 1, 'if 문', '조건이 참인지 확인하고 상황에 맞는 코드를 선택합니다.', 'challenge', 'temperature = 24\nif temperature >= 20:\n    print("따뜻해요")\nelse:\n    print("시원해요")', '따뜻해요', { prompt: 'temperature를 낮은 값으로 바꾸어 if와 else의 다른 메시지를 확인하세요.', hint: 'temperature = 줄의 숫자와 temperature >= 20 조건을 찾으세요. 20보다 작은 온도로 바꾼 뒤 다시 실행해 else의 “시원해요”가 출력되는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: 'if와 else 조건에 따라 다른 메시지를 확인했어요.' }] }),
  makeLesson(7, 2, 'while 문', '조건이 참인 동안 같은 코드를 반복합니다. 반복이 끝나는 변화도 꼭 넣어요.', 'challenge', 'count = 1\nwhile count <= 3:\n    print("연습", count)\n    count += 1', '연습 1\n연습 2\n연습 3', { prompt: 'while 조건의 끝 숫자를 5로 바꾸어 연습 메시지가 5번 출력되게 하세요.', hint: 'while count <= 3: 줄의 기준 숫자 3을 찾으세요. 5로 바꾼 뒤 다시 실행해 연습 1부터 연습 5까지 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: '연습 1\n연습 2\n연습 3\n연습 4\n연습 5', feedback: 'while 반복을 안전하게 끝냈어요.' }] }),
  makeLesson(7, 3, 'for 루프', '목록이나 range의 값을 하나씩 꺼내 같은 작업을 반복합니다.', 'challenge', 'for number in range(1, 6):\n    print(number)', '1\n2\n3\n4\n5', { prompt: 'range를 고쳐 1부터 10까지 모든 숫자가 출력되게 하세요.', hint: 'for 줄의 range(1, 6)에서 끝 숫자 6을 찾으세요. 끝 숫자를 11로 바꾼 뒤 다시 실행해 1부터 10까지 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: '1\n2\n3\n4\n5\n6\n7\n8\n9\n10', feedback: 'for 루프로 1부터 10까지 순회했어요.' }] }),
  makeLesson(7, 4, 'break 문', 'break는 반복을 즉시 멈춥니다. 원하는 대상을 찾았을 때 유용합니다.', 'challenge', 'for number in range(1, 10):\n    if number == 4:\n        print("찾았어요", number)\n        break', '찾았어요 4', { prompt: 'if 조건의 멈출 숫자를 7로 바꾸어 break가 7에서 실행되게 하세요.', hint: 'if number == 4:의 비교 숫자와 print()의 숫자 위치를 찾으세요. 두 4를 7로 바꾼 뒤 다시 실행해 “찾았어요 7”에서 반복이 멈추는지 관찰하세요.', checks: [{ mode: 'equals', value: '찾았어요 7', feedback: 'break 시점을 바꿨어요.' }] }),
  makeLesson(7, 5, 'continue 문', 'continue는 현재 반복만 건너뛰고 다음 반복으로 이동합니다.', 'challenge', 'for number in range(1, 6):\n    if number == 3:\n        continue\n    print(number)', '1\n2\n4\n5', { prompt: 'if 조건의 건너뛸 숫자를 4로 바꾸고, 출력에서 4만 빠지는지 확인하세요.', hint: 'continue 바로 앞 if number == 3:의 비교 숫자를 찾으세요. 3을 4로 바꾼 뒤 다시 실행해 1, 2, 3, 5만 출력되는지 관찰하세요.', checks: [{ mode: 'equals', value: '1\n2\n3\n5', feedback: '반복 한 번을 건너뛰었어요.' }] }),
  makeLesson(7, 6, '흐름 제어 실습', '조건과 반복을 함께 사용해 짝수만 골라 출력합니다.', 'challenge', 'for number in range(1, 11):\n    if number % 2 == 0:\n        print(number)', '2\n4\n6\n8\n10', { prompt: 'range의 범위를 30까지 넓히고, 나머지가 0인 3의 배수만 출력하세요.', hint: 'for 줄의 range 끝 숫자와 if 줄의 number % 2 == 0 조건을 찾으세요. 끝 숫자를 31, 비교 기준을 3으로 바꾼 뒤 다시 실행해 3의 배수만 보이는지 관찰하세요.', checks: [{ mode: 'equals', value: '3\n6\n9\n12\n15\n18\n21\n24\n27\n30', feedback: '조건과 반복으로 여러 값을 골랐어요.' }] }),
]);
