import { chapter, makeLesson } from './lessonFactory';

export const chapter11 = chapter(11, '실생활 문제 해결', [
  makeLesson(11, 1, '문제 정의', '학교 축제 준비물 관리 문제를 데이터와 필요한 기능으로 나누어 봅니다.', 'read', undefined, undefined, undefined, [{ type: 'explanation', title: '문제를 쪼개기', body: '무엇을 입력받고, 어떤 기준으로 판단하고, 어떤 결과를 보여 줄지 먼저 적습니다.' }, { type: 'tip', title: '이번 프로젝트', body: '준비물 재고와 필요한 수량을 비교해 부족한 물건을 찾는 프로그램을 만듭니다.' }]),
  makeLesson(11, 2, '첫 번째 버전: 목록 출력', '가장 작은 프로그램으로 준비물 이름을 먼저 출력합니다.', 'challenge', 'supplies = ["색종이", "가위", "테이프"]\nfor item in supplies:\n    print("준비물:", item)', '준비물: 색종이\n준비물: 가위\n준비물: 테이프', { prompt: 'supplies 리스트에 축제 준비물 하나를 더 추가해 목록 출력 결과를 바꾸세요. 새 항목은 for 문이 자동으로 읽어 한 줄로 보여야 합니다.', hint: '첫 줄의 supplies 리스트 안에서 "색종이", "가위", "테이프" 뒤에 문자열을 하나 더 적으세요. 다시 실행한 뒤 출력창에 기존 세 줄과 새 준비물 한 줄이 차례로 나타나는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '첫 번째 버전에 새 준비물을 추가했어요.' }] }),
  makeLesson(11, 3, '두 번째 버전: 필요한 양 비교', '재고와 계획을 딕셔너리로 담고 부족한지 비교합니다.', 'challenge', 'stock = {"색종이": 30}\nneeded = {"색종이": 50}\nfor item, amount in needed.items():\n    if stock.get(item, 0) < amount:\n        print("준비 필요:", item)\n    else:\n        print("준비 완료:", item)', '준비 필요: 색종이', { prompt: 'stock과 needed 딕셔너리에 가위를 추가해 재고와 필요한 양을 비교하세요. 가위의 수량은 일부러 다르게 정해 부족 또는 완료 안내가 나오게 하세요.', hint: '첫째 줄 stock에 가위 재고를, 둘째 줄 needed에 가위 필요 수량을 각각 추가하세요. 다시 실행해 출력창에 색종이 결과와 함께 가위의 "준비 필요" 또는 "준비 완료" 한 줄이 더 나타나는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '새 물건의 재고와 필요한 양을 비교했어요.' }] }),
  makeLesson(11, 4, '세 번째 버전: 함수로 정리', '반복되는 비교를 함수로 묶으면 다른 준비물에도 재사용할 수 있습니다.', 'challenge', 'def check_missing(stock, plan):\n    missing = []\n    for item, amount in plan.items():\n        if stock.get(item, 0) < amount:\n            missing.append(item)\n    return missing\n\nprint(check_missing({"색종이": 30}, {"색종이": 50}))', '[\'색종이\']', { prompt: 'check_missing()에 테이프도 부족한 상황을 데이터로 추가하세요. 함수의 반복·조건 코드는 그대로 두고 두 딕셔너리의 항목만 바꾸면 됩니다.', hint: '마지막 print()의 check_missing() 호출에서 첫 번째 딕셔너리 stock과 두 번째 딕셔너리 plan에 각각 테이프 수량을 넣으세요. 다시 실행해 반환 목록에 "색종이"와 "테이프"가 함께 보이고, 부족한 준비물이 늘어났는지 관찰하세요.', checks: [{ mode: 'contains', value: '테이프', feedback: '테이프 부족 결과를 확인했어요.' }, { mode: 'changed', value: '', feedback: '함수가 여러 준비물의 부족 여부를 확인했어요.' }] }),
  makeLesson(11, 5, '네 번째 버전: 결과 안내', '찾은 부족 목록을 for 문으로 읽기 좋은 안내문으로 바꿉니다.', 'challenge', 'missing = ["색종이", "테이프"]\nfor item in missing:\n    print("준비 필요:", item)', '준비 필요: 색종이\n준비 필요: 테이프', { prompt: 'missing 목록에 준비가 끝난 물건을 추가하고, 그 물건이 다른 안내문으로 표시되게 하세요. 기존 부족 물건의 출력은 유지하면서 결과를 한 줄 이상 늘려 보세요.', hint: 'missing 리스트와 for 문을 살펴본 뒤, 기존 두 줄 아래에 준비 완료를 알리는 print() 한 줄을 추가하세요. 다시 실행해 출력창에 두 개의 "준비 필요" 줄과 새 "준비 완료" 안내가 함께 보이는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '준비가 끝난 물건 안내도 추가했어요.' }] }),
  makeLesson(11, 6, '개선 아이디어', '입력 검증, 정렬, 더 친절한 안내처럼 다음 버전의 아이디어를 적어 봅니다.', 'read'),
  makeLesson(11, 7, '개발 단계 돌아보기', '문제 정의 → 작은 실행 → 함수와 자료 구조로 개선하는 과정을 되돌아봅니다.', 'challenge', 'steps = ["문제 정의", "작은 실행", "테스트", "개선"]\nfor step in steps:\n    print(step)', '문제 정의\n작은 실행\n테스트\n개선', { prompt: 'steps 리스트에 나만의 개발 단계를 하나 추가하세요. for 문은 그대로 두고 단계의 순서를 생각해 프로그램 과정을 완성해 보세요.', hint: '첫 줄의 steps 리스트에서 "개선" 뒤에 예를 들어 "발표"처럼 문자열을 하나 더 적으세요. 다시 실행해 출력창 맨 아래에 새 단계가 한 줄로 나타나고 앞 단계의 순서가 유지되는지 관찰하세요.', checks: [{ mode: 'appended', value: '', feedback: '나만의 개발 단계를 순서대로 추가했어요.' }] }),
  makeLesson(11, 8, '프로젝트 완성', '자료 구조·함수·조건·반복을 모두 연결한 최종 프로그램을 실행합니다.', 'challenge', 'supplies = {"색종이": 30, "가위": 4, "테이프": 2}\nneeded = {"색종이": 50, "가위": 4, "테이프": 3}\n\ndef check_missing(stock, plan):\n    return [item for item, amount in plan.items() if stock.get(item, 0) < amount]\n\nfor item in check_missing(supplies, needed):\n    print("준비 필요:", item)', '준비 필요: 색종이\n준비 필요: 테이프', { prompt: '준비 필요 결과가 달라지도록 supplies와 needed의 항목 또는 수량을 나의 축제 준비에 맞게 바꾸세요. 함수와 for 문은 유지하고, 재고가 필요한 양보다 적은 물건의 목록을 새로 만들어 보세요.', hint: '위쪽 supplies 딕셔너리와 needed 딕셔너리에서 준비물 이름이나 숫자를 찾아 한두 곳만 바꾸세요. 다시 실행해 출력창의 "준비 필요:" 줄이 달라지고, 바꾼 재고·필요 수량이 결과에 반영되는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '나의 준비물과 수량으로 프로젝트 결과를 바꿨어요.' }] }),
]);
