import { chapter, makeLesson } from './lessonFactory';

export const chapter10 = chapter(10, '자료 구조', [
  makeLesson(10, 1, '리스트', '리스트는 순서가 있는 여러 값을 한 번에 담는 상자입니다.', 'challenge', 'colors = ["빨강", "초록", "파랑"]\nprint(colors[0])\nprint(len(colors))', '빨강\n3', { prompt: 'colors 리스트에 좋아하는 색을 하나 추가하고, 리스트의 길이가 4가 되는지 확인하세요.', hint: 'colors = 리스트의 닫는 대괄호 앞을 찾으세요. `"노랑"`처럼 항목을 하나 추가한 뒤 다시 실행해 길이가 4로 바뀌는지 관찰하세요. 현재 코드는 목록 전체가 아니라 첫 항목과 길이를 보여 줍니다.', sourcePatterns: ['colors', 'len\\s*\\(\\s*colors', '(?:append\\s*\\(|colors\\s*=)'], checks: [{ mode: 'contains', value: '4', feedback: '리스트의 크기가 늘었어요.' }, { mode: 'changed', value: '', feedback: '좋아하는 색을 추가해 리스트 크기가 늘었어요.' }] }),
  makeLesson(10, 2, '객체와 클래스 더 알아보기', '클래스는 비슷한 객체를 만들 때 쓰는 설계도예요. 자료 구조 필수 흐름을 마친 뒤 궁금할 때 짧은 예를 읽어 보세요.', 'optional'),
  makeLesson(10, 3, '튜플', '튜플은 여러 값을 순서대로 담지만 만든 뒤 내용을 바꾸지 않는 묶음입니다. 시작 코드에서는 point 이름에 새 튜플을 다시 넣어 좌표를 바꿔 봅니다.', 'challenge', 'point = (3, 5)\nprint("x:", point[0])\nprint("y:", point[1])', 'x: 3\ny: 5', { prompt: 'point 이름에 다른 좌표 튜플을 다시 넣고, x와 y 출력이 달라지는지 확인하세요.', hint: 'point = (3, 5) 줄의 괄호 안 두 숫자를 바꾸세요. 튜플 안의 값을 나중에 직접 고치는 것이 아니라, 처음부터 다른 튜플을 point에 넣는 방식입니다.', sourcePatterns: ['point\\s*=','point\\[0\\]', 'point\\[1\\]', 'print\\s*\\('], checks: [{ mode: 'contains', value: 'x:', feedback: '튜플의 위치별 값을 꺼냈어요.' }, { mode: 'changed', value: '', feedback: '새 튜플의 좌표를 위치별로 꺼냈어요.' }] }),
  makeLesson(10, 4, '딕셔너리', '딕셔너리는 key와 value를 짝으로 저장해 이름표로 값을 찾습니다. 과목별 점수를 출력하며 자료 구조를 확인합니다.', 'challenge', 'scores = {"수학": 90, "과학": 85}\nfor subject, score in scores.items():\n    print(subject, score)', '수학 90\n과학 85', { prompt: 'scores 딕셔너리에 좋아하는 과목과 점수 한 쌍을 추가하고, 순회 결과에 새 줄이 나타나게 하세요.', hint: 'scores = 딕셔너리의 마지막 항목 뒤를 찾으세요. 쉼표와 "과목": 점수 쌍을 추가한 뒤 다시 실행해 새 과목과 점수가 한 줄 출력되는지 관찰하세요.', sourcePatterns: ['scores\\s*=', 'scores\\.items\\s*\\(', 'for\\s+subject'], checks: [{ mode: 'appended', value: '', feedback: '새 과목과 점수를 한 줄 추가했어요.' }] }),
  makeLesson(10, 5, '목록을 하나씩 살펴보기', 'for 문으로 리스트의 항목을 하나씩 꺼내면 목록 전체를 다룰 수 있습니다.', 'challenge', 'todos = ["수학 숙제", "물 마시기"]\nfor todo in todos:\n    print("할 일:", todo)', '할 일: 수학 숙제\n할 일: 물 마시기', { prompt: 'todos 리스트에 할 일을 하나 더 추가하고, for 루프가 새 항목도 출력하는지 확인하세요.', hint: 'todos = 리스트의 닫는 대괄호 앞을 찾으세요. 쉼표와 새 할 일 문자열을 추가한 뒤 다시 실행해 “할 일:” 줄이 하나 더 나오는지 관찰하세요.', sourcePatterns: ['todos\\s*=', 'for\\s+todo\\s+in\\s+todos', '할 일'], checks: [{ mode: 'appended', value: '', feedback: '새 할 일을 추가하고 목록을 순회했어요.' }] }),
  makeLesson(10, 7, '참조 더 알아보기', '참조는 두 이름이 같은 리스트를 가리키는 상황이에요. 한쪽에서 리스트를 바꾸면 다른 이름으로 볼 때도 바뀐 내용이 보일 수 있어요. 궁금할 때 짧은 예를 읽어 보세요.', 'optional'),
  makeLesson(10, 8, '문자열 더 알아보기', '문자열도 순서가 있는 시퀀스라 인덱스, len(), upper() 등을 사용할 수 있습니다.', 'challenge', 'word = "python"\nprint(word[0])\nprint(word.upper())\nprint(len(word))', 'p\nPYTHON\n6', { prompt: 'word를 한 글자 이상인 다른 영어 단어로 바꾸고, 첫 글자·대문자·길이가 새 단어에 맞게 나오는지 관찰하세요.', hint: 'word = 줄의 따옴표 안 python을 찾으세요. 한 글자 이상인 다른 영어 단어로 바꾼 뒤 다시 실행해 세 출력이 새 단어에 맞는지 관찰하세요.', sourcePatterns: ['word\\s*=', 'word\\[0\\]', 'word\\.upper\\s*\\(', 'len\\s*\\('], checks: [{ mode: 'changed', value: '', feedback: '다른 문자열의 여러 기능을 사용했어요.' }] }),
]);
