import { chapter, makeLesson } from './lessonFactory';

export const chapter8 = chapter(8, '함수', [
  makeLesson(8, 1, '함수와 매개변수', 'def로 자주 쓸 동작을 묶고 매개변수로 재료를 받습니다.', 'challenge', 'def greet(name):\n    print("안녕,", name)\n\ngreet("민준")', '안녕, 민준', { prompt: 'greet 함수를 다른 이름으로 호출하고, 매개변수에 전달한 이름이 출력되는지 확인하세요.', hint: '코드 아래쪽 greet("민준") 호출의 괄호 안 문자열을 찾으세요. 이름을 바꾼 뒤 다시 실행해 인사 결과에도 새 이름이 나타나는지 관찰하세요.', checks: [{ mode: 'contains', value: '안녕', feedback: '함수에 입력을 전달했어요.' }, { mode: 'changed', value: '', feedback: '다른 이름을 함수에 전달했어요.' }] }),
  makeLesson(8, 2, '지역 변수', '함수 안에서 만든 변수는 그 함수 안에서 주로 사용됩니다.', 'challenge', 'def make_message():\n    message = "함수 안의 메시지"\n    return message\n\nprint(make_message())', '함수 안의 메시지', { prompt: 'message가 돌려줄 문장을 바꾸고, 함수 호출 결과가 새 문장으로 나오는지 확인하세요.', hint: '함수 안 message = 줄 또는 return 뒤에 있는 문자열을 찾으세요. 따옴표 안 문장만 바꾼 뒤 다시 실행해 print(make_message())의 결과가 달라지는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '함수가 돌려줄 나만의 메시지를 만들었어요.' }] }),
  makeLesson(8, 3, 'global은 신중하게', '바깥 변수와 안쪽 변수를 섞기보다 매개변수와 return으로 값을 주고받는 편이 안전합니다.', 'read'),
  makeLesson(8, 4, '기본 인수', '매개변수에 기본값을 정하면 입력을 생략해도 함수가 동작합니다.', 'challenge', 'def cheer(name="친구"):\n    print(name, "힘내!")\n\ncheer()\ncheer("지우")', '친구 힘내!\n지우 힘내!', { prompt: 'cheer 함수의 기본 이름을 바꾸고, 값을 생략한 호출의 결과가 달라지는지 확인하세요.', hint: 'def cheer(name="친구"): 줄의 기본값 문자열을 찾으세요. 이름만 바꾼 뒤 다시 실행해 cheer() 줄은 새 이름, cheer("지우") 줄은 지우로 남는지 관찰하세요.', checks: [{ mode: 'contains', value: '힘내', feedback: '기본 인수를 사용했어요.' }, { mode: 'changed', value: '', feedback: '기본 인수를 나만의 이름으로 바꿨어요.' }] }),
  makeLesson(8, 5, '키워드 인수', '매개변수 이름을 함께 적으면 순서를 헷갈리지 않고 값을 전달할 수 있습니다.', 'challenge', 'def profile(name, grade):\n    print(name, grade, "학년")\n\nprofile(grade=2, name="민준")', '민준 2 학년', { prompt: 'profile 호출의 name과 grade 키워드 값을 나에게 맞게 바꾸고 결과를 확인하세요.', hint: 'profile(grade=2, name="민준") 괄호 안의 두 키워드 값을 찾으세요. 이름과 학년 숫자를 바꾼 뒤 다시 실행해 키워드 이름에 맞는 순서로 출력되는지 관찰하세요.', checks: [{ mode: 'contains', value: '학년', feedback: '키워드로 값을 전달했어요.' }, { mode: 'changed', value: '', feedback: '나에게 맞는 키워드 인수 값을 전달했어요.' }] }),
  makeLesson(8, 6, '가변 인수', '몇 개가 들어올지 모르는 값은 *args로 받아 반복할 수 있습니다.', 'challenge', 'def total(*numbers):\n    return sum(numbers)\n\nnumbers = (2, 3, 5)\nprint("숫자 개수:", len(numbers))\nprint("합계:", total(*numbers))', '숫자 개수: 3\n합계: 10', { prompt: 'numbers 묶음에 숫자 하나를 더 넣고, 개수와 합계가 함께 바뀌는지 확인하세요.', hint: 'numbers = (2, 3, 5) 줄의 닫는 괄호 앞을 찾으세요. 쉼표와 숫자를 하나 추가한 뒤 다시 실행해 숫자 개수가 4가 되고 합계도 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: '숫자 개수: 4', feedback: '숫자를 하나 더 넣었어요.' }, { mode: 'changed', value: '', feedback: '추가한 숫자까지 합계를 확인했어요.' }] }),
  makeLesson(8, 7, 'return', 'return은 함수의 계산 결과를 호출한 곳으로 돌려줍니다.', 'challenge', 'def average(a, b):\n    return (a + b) / 2\n\nprint("평균:", average(80, 90))', '평균: 85.0', { prompt: 'average 호출에 다른 두 점수를 넣고, return이 계산한 평균을 확인하세요.', hint: 'print() 안 average(80, 90) 호출의 두 숫자를 찾으세요. 두 점수를 바꾼 뒤 다시 실행해 평균 출력 값도 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: '평균', feedback: 'return 결과를 사용했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 점수의 평균을 계산했어요.' }] }),
  makeLesson(8, 8, '문서 문자열', '함수 첫 줄의 설명 문자열은 함수의 목적을 알려 주는 작은 안내문입니다.', 'challenge', 'def square(number):\n    """숫자를 제곱해 돌려줘요."""\n    return number ** 2\n\nprint(square(4))', '16', { prompt: 'square 함수에 넣을 숫자를 바꾸고, 제곱 결과가 새 값으로 나오는지 확인하세요.', hint: 'print(square(4)) 호출의 괄호 안 숫자를 찾으세요. 숫자를 바꾼 뒤 다시 실행해 return된 제곱 결과가 달라지는지 관찰하세요.', checks: [{ mode: 'changed', value: '', feedback: '바꾼 숫자의 제곱 결과를 확인했어요.' }] }),
  makeLesson(8, 9, '함수 확인 실습', '할인 가격 함수를 만들며 입력·처리·결과의 흐름을 정리합니다.', 'challenge', 'def discount(price, rate):\n    return price * (1 - rate / 100)\n\nprint("할인 가격:", int(discount(10000, 20)))', '할인 가격: 8000', { prompt: 'discount 호출의 가격이나 할인율을 바꾸고, 함수가 새 할인 가격을 계산하는지 확인하세요.', hint: 'print() 안 discount(10000, 20) 호출의 두 숫자를 찾으세요. 가격 또는 할인율을 바꾼 뒤 다시 실행해 할인 가격 출력이 달라지는지 관찰하세요.', checks: [{ mode: 'contains', value: '할인 가격', feedback: '함수로 계산을 재사용했어요.' }, { mode: 'changed', value: '', feedback: '바꾼 가격과 할인율로 다시 계산했어요.' }] }),
]);
