import type { GlossaryItem } from './types';

type Term = GlossaryItem;

const catalog: Record<string, Term> = {
  'print()': { term: 'print()', definition: '괄호 안의 값을 화면에 보여 주는 함수' },
  'len()': { term: 'len()', definition: '문자열이나 묶음에 들어 있는 항목 수를 세는 함수' },
  'sum()': { term: 'sum()', definition: '숫자 묶음의 합계를 구하는 함수' },
  'int()': { term: 'int()', definition: '값을 정수로 바꾸는 함수이며 소수 부분을 반올림하지 않고 버려요' },
  'round()': { term: 'round()', definition: 'round(3.14159, 2)는 소수 둘째 자리까지 정리한 3.14예요. 정확히 중간이면 가까운 짝수 쪽으로 정리해요' },
  'type()': { term: 'type()', definition: '값의 자료형을 알려 주는 함수' },
  'dir()': { term: 'dir()', definition: '모듈이나 객체에서 사용할 수 있는 이름을 목록으로 보여 주는 함수' },
  'range()': { term: 'range()', definition: '일정한 규칙의 숫자 범위를 만드는 도구이며 끝 숫자는 포함하지 않아요' },
  for: { term: 'for', definition: '묶음에서 값을 하나씩 꺼내 같은 코드를 반복하는 문법' },
  in: { term: 'in', definition: '값이 묶음 안에 있는지 확인하거나 for가 값을 꺼낼 대상을 나타내는 연산자' },
  if: { term: 'if', definition: '조건이 참일 때 들여쓴 코드를 실행하는 문법' },
  else: { term: 'else', definition: 'if 조건이 거짓일 때 실행할 부분을 시작하는 말' },
  while: { term: 'while', definition: '조건이 참인 동안 같은 코드를 반복하는 문법' },
  break: { term: 'break', definition: '반복을 바로 끝내는 명령' },
  continue: { term: 'continue', definition: '현재 반복만 건너뛰고 다음 반복으로 가는 명령' },
  return: { term: 'return', definition: '함수의 결과를 호출한 곳으로 돌려주는 명령' },
  def: { term: 'def', definition: '새 함수를 만들기 시작한다는 표시' },
  import: { term: 'import', definition: '모듈을 가져와 사용할 준비를 하는 명령' },
  'from ... import': { term: 'from ... import', definition: '모듈에서 필요한 이름만 골라 가져오는 문법' },
  list: { term: '리스트', definition: '여러 값을 순서대로 담는 자료 구조' },
  변수: { term: '변수', definition: '값을 담아 두는 이름표' },
  문자열: { term: '문자열', definition: '따옴표로 감싼 글자 묶음' },
  tuple: { term: '튜플', definition: '여러 값을 순서대로 담고 만든 뒤 내용을 바꾸지 않는 묶음' },
  dict: { term: '딕셔너리', definition: '이름표(key)와 값(value)을 짝으로 저장하는 자료 구조' },
  key: { term: 'key', definition: '딕셔너리에서 값을 찾는 이름표(key)' },
  value: { term: 'value', definition: 'key에 연결되어 저장된 실제 값(value)' },
  index: { term: '인덱스', definition: '묶음에서 값의 위치를 나타내는 번호이며 보통 0부터 시작해요' },
  'items()': { term: 'items()', definition: '딕셔너리의 key와 value를 한 쌍씩 꺼내는 메서드' },
  'get()': { term: 'get()', definition: '딕셔너리에서 key의 값을 찾고, 없으면 정한 기본값을 돌려주는 메서드' },
  메서드: { term: '메서드', definition: '값 뒤에 점(.)으로 붙여 쓰는 기능' },
  'append()': { term: 'append()', definition: '리스트 끝에 값 하나를 추가하는 메서드' },
  'upper()': { term: 'upper()', definition: '문자열의 영어 글자를 대문자로 바꾸는 메서드' },
  '리스트 컴프리헨션': { term: '리스트 컴프리헨션', definition: 'for와 if를 대괄호 안에 써서 새 리스트를 짧게 만드는 표현' },
  언패킹: { term: '언패킹', definition: '묶음의 여러 값을 여러 변수에 차례로 나누어 담는 방법' },
  '빈 리스트 조건': { term: '빈 리스트 조건', definition: 'if에서 빈 리스트는 거짓으로, 항목이 있는 리스트는 참으로 판단되는 흐름' },
  'math.sqrt()': { term: 'math.sqrt()', definition: 'math 모듈에서 0 이상인 수의 음이 아닌 제곱근을 구하는 함수' },
  sqrt: { term: 'sqrt', definition: '자기 자신을 곱해 원래 수가 되는 음이 아닌 제곱근을 구하는 도구의 이름이에요. "sqrt"는 이름이고, math.sqrt(25)처럼 괄호와 값을 붙여 호출하면 5.0을 계산해요' },
  'math.pi': { term: 'math.pi', definition: 'math 모듈에 들어 있는 원주율 값으로 약 3.14159예요' },
  pi: { term: 'pi', definition: '원의 둘레를 지름으로 나눈 원주율을 가리키는 이름' },
  math: { term: 'math', definition: '제곱근·원주율 같은 수학 도구를 모아 둔 표준 모듈' },
  '**': { term: '**', definition: '왼쪽 수를 오른쪽 횟수만큼 거듭제곱하는 연산자' },
  '*numbers': { term: '*numbers', definition: '묶음 numbers의 값을 함수 인수로 하나씩 펼쳐 전달하는 표현' },
  '=': { term: '=', definition: '오른쪽 값을 왼쪽 변수에 넣는 할당 기호' },
  '+': { term: '+', definition: '두 수를 더하거나 문자열을 이어 붙이는 연산자' },
  '-': { term: '-', definition: '왼쪽 수에서 오른쪽 수를 빼는 연산자' },
  '*': { term: '*', definition: '두 수를 곱하는 연산자' },
  '/': { term: '/', definition: '나눗셈 결과를 계산하는 연산자' },
  '//': { term: '//', definition: '나눗셈의 몫을 구하는 연산자' },
  '%': { term: '%', definition: '나눗셈 뒤에 남는 나머지를 구하는 연산자' },
  '+=': { term: '+=', definition: '현재 값에 오른쪽 값을 더해 다시 저장하는 기호' },
  '-=': { term: '-=', definition: '현재 값에서 오른쪽 값을 빼 다시 저장하는 기호' },
  '==': { term: '==', definition: '왼쪽과 오른쪽 값이 같은지 비교하는 기호' },
  '>=': { term: '>=', definition: '왼쪽 값이 오른쪽 값보다 크거나 같은지 비교하는 기호' },
  '<=': { term: '<=', definition: '왼쪽 값이 오른쪽 값보다 작거나 같은지 비교하는 기호' },
  '<': { term: '<', definition: '왼쪽 값이 오른쪽 값보다 작은지 비교하는 기호' },
  True: { term: 'True', definition: '조건이 참임을 나타내는 값' },
  False: { term: 'False', definition: '조건이 거짓임을 나타내는 값' },
  'dir(math)': { term: 'dir(math)', definition: 'math 모듈에서 사용할 수 있는 이름 목록을 보여 달라는 호출' },
  'math.sqrt(25)': { term: 'math.sqrt(25)', definition: 'math 모듈의 sqrt 함수에 25를 넣어 제곱근 5.0을 계산하는 호출' },
};

const termsByLesson: Record<string, string[]> = {
  'chapter-1-4': ['print()'], 'chapter-2-2': ['=', '변수', '문자열', 'print()'], 'chapter-2-3': ['list', 'for', 'in', '변수', '문자열', 'print()'],
  'chapter-3-3': ['=', '변수', '문자열', 'print()'], 'chapter-3-4': ['list', 'for', 'in', '변수', '문자열', 'print()'],
  'chapter-4-3': ['=', '변수', '문자열', 'print()'], 'chapter-4-4': ['=', '변수', '문자열', 'print()'], 'chapter-4-5': ['=', '변수', '문자열', 'print()'],
  'chapter-5-1': ['print()'], 'chapter-5-2': ['=', 'print()'], 'chapter-5-3': ['=', 'print()'], 'chapter-5-4': ['print()'], 'chapter-5-5': ['=', 'print()'],
  'chapter-5-6': ['type()', 'print()'], 'chapter-5-7': ['=', 'if', 'True', 'print()'], 'chapter-5-8': ['=', '변수', '문자열', 'print()'],
  'chapter-6-1': ['=', '//', '%', 'print()'], 'chapter-6-2': ['=', '+=', '-=', 'print()'], 'chapter-6-3': ['=', '+', '*', 'print()'],
  'chapter-6-4': ['=', '*', '-', 'print()'], 'chapter-6-5': ['=', '+', '*', 'print()'],
  'chapter-7-1': ['=', 'if', 'else', '>=', 'print()'], 'chapter-7-2': ['=', 'while', '<=', '+=', 'print()'],
  'chapter-7-3': ['for', 'in', 'range()', 'print()'], 'chapter-7-4': ['for', 'in', 'range()', 'if', '==', 'break', 'print()'],
  'chapter-7-5': ['for', 'in', 'range()', 'if', '==', 'continue', 'print()'], 'chapter-7-6': ['for', 'in', 'range()', 'if', '%', '==', 'print()'],
  'chapter-8-1': ['def', 'print()'], 'chapter-8-2': ['def', 'return', 'print()'], 'chapter-8-4': ['def', 'print()'], 'chapter-8-5': ['def', '=', 'print()'],
  'chapter-8-6': ['def', 'return', 'sum()', 'len()', 'tuple', '*numbers', 'print()'], 'chapter-8-7': ['def', 'return', '+', '/', 'print()'],
  'chapter-8-8': ['def', 'return', '**', 'print()'], 'chapter-8-9': ['def', 'return', 'int()', '/', '*', '-', 'print()'],
  'chapter-9-1': ['import', 'math', 'math.sqrt()', 'print()'], 'chapter-9-2': ['from ... import', 'pi', 'round()', 'print()'],
  'chapter-9-5': ['import', 'math', 'dir()', 'dir(math)', 'in', 'sqrt', 'math.sqrt(25)', 'pi', 'True', 'False', 'print()'],
  'chapter-9-7': ['import', 'math', 'math.pi', 'round()', '**', '*', 'print()'],
  'chapter-10-1': ['list', 'index', 'len()', 'print()'], 'chapter-10-3': ['tuple', 'index', 'print()'], 'chapter-10-4': ['dict', 'key', 'value', 'for', 'in', 'items()', '언패킹', 'print()'],
  'chapter-10-5': ['list', 'for', 'in', 'print()'], 'chapter-10-7': ['list', 'append()', '메서드', 'for', 'in', 'print()'],
  'chapter-10-8': ['index', 'len()', 'upper()', 'print()'], 'chapter-10-9': ['dict', 'key', 'value', 'for', 'in', 'items()', '언패킹', 'print()'],
  'chapter-11-2': ['list', 'for', 'in', 'print()'], 'chapter-11-3': ['dict', 'for', 'in', 'items()', 'get()', '메서드', 'if', 'else', '<', '언패킹', 'print()'],
  'chapter-11-4': ['dict', 'list', 'key', 'value', 'def', 'return', 'for', 'in', 'items()', 'get()', 'append()', '메서드', 'if', '<', '언패킹', 'print()'], 'chapter-11-5': ['list', 'for', 'in', 'print()'],
  'chapter-11-7': ['list', 'for', 'in', 'print()'], 'chapter-11-8': ['dict', 'key', 'value', 'def', 'return', '리스트 컴프리헨션', 'for', 'in', 'items()', 'get()', '메서드', 'if', 'else', '<', '언패킹', '빈 리스트 조건', 'print()'],
};

const aliases: Record<string, string[]> = {
  for: ['for ... in', 'for 루프'],
  in: ['for ... in'],
  'math.sqrt()': ['math.sqrt(x)'],
  'get()': ['stock.get()'],
  'append()': ['리스트.append()'],
  'range()': ['range'],
  리스트: ['list'],
  튜플: ['tuple'],
  딕셔너리: ['dict'],
};

export function mergeCodeGlossary(lessonId: string, existing: GlossaryItem[]): GlossaryItem[] {
  const known = new Set(existing.map((item) => item.term));
  const additions = (termsByLesson[lessonId] ?? [])
    .map((term) => catalog[term])
    .filter((item): item is Term => Boolean(item) && !known.has(item.term) && !(aliases[item.term] ?? []).some((alias) => known.has(alias)));
  return [...existing, ...additions];
}
