import type { Lesson } from '../../content/types';

interface Props { lesson: Lesson; completed: boolean; canComplete: boolean; onComplete: () => void; onPrevious: () => void; onNext: () => void; hasPrevious: boolean; hasNext: boolean; }

export function LessonContent({ lesson, completed, canComplete, onComplete, onPrevious, onNext, hasPrevious, hasNext }: Props) {
  const bannerSrc = `${import.meta.env.BASE_URL}assets/python-learning-banner.png`;
  const conceptLabel = (type: string) => ({ example: '예제', tip: '기억하기', warning: '주의', explanation: '핵심 개념' }[type] ?? '핵심 개념');
  return <article className="lesson-content">
    {lesson.chapter === 2 && <div className="learning-banner"><img src={bannerSrc} alt="노트북으로 파이썬을 배우는 학생" onError={(event) => { event.currentTarget.style.display = 'none'; }} /><div className="banner-fallback"><span>파이썬</span><strong>오늘의 첫 코드</strong><p>생각을 코드로 바꿔 보세요.</p></div><div className="banner-copy"><span className="chapter-kicker">{lesson.chapter}단원</span><strong>처음 만나는<br />파이썬</strong><span className="banner-note">한 줄씩, 직접 실행해요</span></div></div>}
    <div className="lesson-heading"><span className="chapter-kicker">{lesson.chapter}단원 · {lesson.order}번째 소단원</span><h2>{lesson.title}</h2><p>{lesson.summary}</p></div>
    <section className="objectives"><h3>오늘 할 일</h3><ul>{lesson.objectives.map((objective) => <li key={objective}><span>✓</span>{objective}</li>)}</ul></section>
    <div className="concept-stack">{lesson.concepts.map((concept, index) => <section className={`concept-block ${concept.type}`} key={`${concept.title ?? concept.type}-${index}`}><div className="concept-label">{conceptLabel(concept.type)}</div><div><h3>{concept.title}</h3><p>{concept.body}</p>{concept.code && <pre aria-label="따라 할 예제 코드"><code>{concept.code}</code></pre>}</div></section>)}</div>
    <section className="glossary-block" aria-labelledby="glossary-title"><div className="concept-label">용어</div><div><h3 id="glossary-title">핵심 용어</h3><dl>{lesson.glossary.map((item) => <div key={item.term}><dt>{item.term}</dt><dd>{item.definition}</dd></div>)}</dl></div></section>
    {lesson.challenge && <section className="challenge-block" aria-labelledby="challenge-title"><div className="challenge-heading"><span className="challenge-icon" aria-hidden="true">✦</span><div><span className="chapter-kicker">직접 해 보기</span><h3 id="challenge-title">도전 과제</h3></div></div><p>{lesson.challenge.prompt}</p><div className="challenge-guidance"><div><h4>도전 순서</h4><ol>{lesson.challenge.steps?.map((step) => <li key={step}>{step}</li>)}</ol></div><div><h4>통과 기준</h4><ul>{lesson.challenge.successCriteria?.map((criterion) => <li key={criterion}>{criterion}</li>)}</ul></div><div><h4>막힐 때</h4><ul>{lesson.challenge.commonMistakes?.map((mistake) => <li key={mistake}>{mistake}</li>)}</ul></div></div><details><summary>힌트 보기</summary><p>{lesson.challenge.hint}</p></details></section>}
    {lesson.resources && <section className="resource-block" aria-labelledby="resource-title"><div className="concept-label">출처</div><div><h3 id="resource-title">교재 출처와 라이선스</h3>{lesson.resources.map((resource) => <a href={resource.href} target="_blank" rel="noreferrer" key={resource.href}>{resource.label}<span>{resource.note ?? '↗'}</span></a>)}</div></section>}
    <footer className="lesson-actions"><button className="secondary-button" onClick={onPrevious} disabled={!hasPrevious}>← 이전</button><button className={`primary-button ${completed ? 'is-complete' : canComplete ? 'gi-pulse' : ''}`} onClick={onComplete} disabled={completed || !canComplete}>{completed ? '✓ 학습 완료됨' : canComplete ? lesson.completion === 'optional' ? '참고 완료' : '학습 완료' : lesson.completion === 'run' ? '코드를 먼저 실행해요' : lesson.completion === 'challenge' ? '도전을 통과해요' : '학습 완료'}</button><button className="secondary-button next-button" onClick={onNext} disabled={!hasNext}>다음 학습 →</button></footer>
  </article>;
}
