import { useEffect, useMemo, useRef, useState } from 'react';
import { lessons, getCompletedLessonCount, getLesson, getNextRequiredLessonIndex, getRequiredLessonCount, isLessonUnlocked } from './content/chapters';
import { useLearningProgress } from './hooks/useLearningProgress';
import { AppHeader } from './components/AppHeader';
import { ChapterNav } from './components/ChapterNav';
import { UpdateHistoryDialog } from './components/UpdateHistoryDialog';
import { LessonWorkspace } from './features/learn/LessonWorkspace';
import { StudentProfileDialog } from './features/submissions/StudentProfileDialog';
import { SubmissionDialog } from './features/submissions/SubmissionDialog';
import { TeacherAdminPanel } from './features/submissions/TeacherAdminPanel';
import { StudentReportDialog } from './features/reports/StudentReportDialog';
import './styles/tokens.css'; import './styles/layout.css'; import './styles/components.css'; import './styles/responsive.css'; import './styles/submissions.css';

const CHAPTER11_NOTICE_KEY = 'python-bite-class-chapter11-notice-v1';
export default function App() {
  const [navOpen, setNavOpen] = useState(false); const [showUpdates, setShowUpdates] = useState(false); const [showProfile, setShowProfile] = useState(false); const [showSubmit, setShowSubmit] = useState(false); const [showAdmin, setShowAdmin] = useState(false); const [showReport, setShowReport] = useState(false); const [reportAfterProfile, setReportAfterProfile] = useState(false); const profileFlowCompletedRef = useRef(false);
  const { progress, completed, activeProfile, profiles, currentLessonId, markComplete, saveCode, saveExecutionEvidence, resetProgress, setCurrentLessonId, createProfile, updateProfile, switchProfile, logout, clearProfile, guestHasProgress } = useLearningProgress();
  const currentId = currentLessonId ?? lessons[0].id; const setCurrentId = setCurrentLessonId;
  const [showChapter11Notice, setShowChapter11Notice] = useState(() => Boolean(localStorage.getItem('python-bite-class-progress-chapter11-v1') && !localStorage.getItem(CHAPTER11_NOTICE_KEY)));
  const index = Math.max(0, lessons.findIndex((item) => item.id === currentId)); const lesson = useMemo(() => getLesson(currentId), [currentId]);
  useEffect(() => { if (!isLessonUnlocked(index, completed)) { const firstOpen = lessons.findIndex((_, lessonIndex) => isLessonUnlocked(lessonIndex, completed)); setCurrentId(lessons[firstOpen < 0 ? 0 : firstOpen].id); } }, [completed, index, setCurrentId]);
  useEffect(() => { if (reportAfterProfile && activeProfile?.school && activeProfile.name) { setReportAfterProfile(false); setShowReport(true); } }, [activeProfile, reportAfterProfile]);
  const navigate = (nextIndex: number) => { const targetIndex = nextIndex > index ? getNextRequiredLessonIndex(index) : nextIndex; const next = lessons[targetIndex]; if (next && isLessonUnlocked(targetIndex, completed)) setCurrentId(next.id); };
  const reset = () => { if (window.confirm('저장된 학습 진도와 코드를 모두 지울까요?')) { resetProgress(); setCurrentId(lessons[0].id); } };
  const dismissChapter11Notice = () => { localStorage.setItem(CHAPTER11_NOTICE_KEY, 'seen'); setShowChapter11Notice(false); };
  const profileLabel = activeProfile?.school && activeProfile.name ? `${activeProfile.school} · ${activeProfile.name}` : undefined;
  const openStudentReport = () => { if (profileLabel) setShowReport(true); else { setReportAfterProfile(true); setShowProfile(true); } };
  return <div className="app-shell"><AppHeader chapter={lesson.chapter} completedCount={getCompletedLessonCount(completed)} total={getRequiredLessonCount()} onMenu={() => setNavOpen((value) => !value)} onUpdates={() => setShowUpdates(true)} menuOpen={navOpen} profileLabel={profileLabel} onLogin={() => setShowProfile(true)} onSubmit={() => setShowSubmit(true)} onTeacher={() => setShowAdmin(true)} />{showChapter11Notice && <aside className="migration-notice" role="status"><div><strong>11단원이 새로 바뀌었어요</strong><p>이전 11단원 기록은 따로 보관하고, 새 실생활 문제 풀이를 시작해요.</p></div><div><button className="primary-button gi-pulse" onClick={() => { setCurrentId('chapter-11-1'); dismissChapter11Notice(); }}>새 11단원 시작하기</button><button className="secondary-button" onClick={dismissChapter11Notice}>닫기</button></div></aside>}<div className="main-grid"><ChapterNav currentId={lesson.id} completed={completed} onSelect={(id) => { const nextIndex = lessons.findIndex((item) => item.id === id); if (isLessonUnlocked(nextIndex, completed)) setCurrentId(id); }} onReset={reset} onReport={openStudentReport} open={navOpen} onClose={() => setNavOpen(false)} onUpdates={() => setShowUpdates(true)} /><LessonWorkspace key={`${activeProfile?.id}:${lesson.id}`} lesson={lesson} index={index} total={lessons.length} completed={completed.has(lesson.id)} savedCode={progress.codeByLesson[lesson.id]} savedEvidence={progress.executionByLesson[lesson.id]} onCodeChange={(code) => saveCode(lesson.id, code)} onExecutionEvidence={(evidence) => saveExecutionEvidence(lesson.id, evidence)} onComplete={() => markComplete(lesson.id)} onNavigate={navigate} /></div>{showUpdates && <UpdateHistoryDialog onClose={() => setShowUpdates(false)} />}{showProfile && <StudentProfileDialog profile={activeProfile} profiles={profiles} guestHasProgress={guestHasProgress} onSave={(school, name) => updateProfile(school, name)} onCreate={(school, name, adoptGuest) => { profileFlowCompletedRef.current = true; createProfile(school, name, adoptGuest); }} onSwitch={(id) => { profileFlowCompletedRef.current = true; switchProfile(id); }} onClose={() => { setShowProfile(false); if (!profileFlowCompletedRef.current) setReportAfterProfile(false); profileFlowCompletedRef.current = false; }} onLogout={logout} onClear={clearProfile} onReport={() => { setShowProfile(false); setShowReport(true); }} />}{showReport && <StudentReportDialog profile={activeProfile?.school && activeProfile.name ? activeProfile : undefined} progress={progress} currentLessonId={currentLessonId} onClose={() => setShowReport(false)} onNeedProfile={() => { setShowReport(false); setReportAfterProfile(true); setShowProfile(true); }} />}{showSubmit && <SubmissionDialog profile={activeProfile?.school && activeProfile.name ? activeProfile : undefined} progress={progress} onClose={() => setShowSubmit(false)} onSubmitted={() => undefined} />}{showAdmin && <TeacherAdminPanel onClose={() => setShowAdmin(false)} />}</div>;
}
